### ISSUE TITLE
Select trigger is not aligned correctly in IE 11

### ISSUE THREAD

**Issue by avber** [vitmalina/w2ui#1448] opened 2017-01-05 07:23 UTC
IE 11
[demo](http://w2ui.com/web/demos/#!forms/forms-2)

**Comment by mpf82** [comment] 2017-01-05 10:55
possible duplicate of https://github.com/vitmalina/w2ui/issues/1268

**Comment by mpf82** [comment] 2021-04-22 14:28
Closing issue: no response, no reproducer, most likely duplicate

**Closed by mpf82** 2021-04-22 14:28 UTC
