### ISSUE TITLE
Collapsing a top-level sidebar node causes an error

### ISSUE THREAD

**Issue by supernifty** [vitmalina/w2ui#1740] opened 2018-02-08 11:51 UTC
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
Collapsing a top-level node in the sidebar raises an exception.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**.
You can navigate the sidebar tree using the keyboard. Left arrow collapses a tree item. But if you attempt to collapse a top-level node that is already collapsed, an exception is raised.

To reproduce, go to the W2UI demos page (http://w2ui.com/web/demos/#!layout/layout-1) and left arrow on one of the top level tree nodes in the sidebar.

* **What is the expected behavior?**
Collapse shouldn't raise an exception.

* **What is the motivation / use case for changing the behavior?**
Some browsers don't behave well when JavaScript throws an exception.

* **Link to jsFiddle that demonstrates the problem:**

* **Other information**
When the nodes are in groups, the issue doesn't occur.

**Comment by mpf82** [comment] 2021-04-26 08:09
I cannot reproduce this issue. Maybe it has been already fixed? Can you please confirm?

**Comment by supernifty** [comment] 2021-04-27 10:43
Looks to me like it's fixed! Thanks for following up.

**Comment by mpf82** [comment] 2021-04-27 12:05
Closing issue: resolved

**Closed by mpf82** 2021-04-27 12:05 UTC
Labels: Bug, Reproducer: Missing, Waiting For Reply
