### ISSUE TITLE
In the GRID Search,, popup after select date close

### ISSUE THREAD

**Issue by Aleksandrs7** [vitmalina/w2ui#1725] opened 2017-12-05 12:33 UTC
If im select search by date.. and select my date... this Searches popup is closed..

In example you are have some problem..

http://jsfiddle.net/ca9hLfp0/

**Comment by mpf82** [comment] 2017-12-05 13:26
Possible duplicate of https://github.com/vitmalina/w2ui/issues/1616

**Closed** 2018-04-23 16:25 UTC
