### ISSUE TITLE
searches toolbar on a grid inside a popup doesn't work

### ISSUE THREAD

**Issue by spizzi77** [vitmalina/w2ui#1235] opened 2016-05-05 12:34 UTC
Hy All, 
First of all thanks for your wonderful work with this plugin, it's really interesting and usefull.
I ask for a problem creating a grid inside a popup, i post under my code, the problem is that the grid show ok inside the popup, all it's ok but the only problem that i found is that the searches input doesn't work in firefox 46, intead in IE9 if do the search it works sometimes but not works right because it's really slow and the digits gone blocked sometimes.Can someone help me?I need that the search toolbar works fine with Firefox 46, IE9 and IE11, inside the popup.
Server side is PHP.

Here's my code
```			
$().w2grid({
		        name: 'gridIntestaSettoristi',
		        msgNotJSON: 'Non ci sono validi risultati',
		        header : 'Risultati Ricerca',
		        show: {
		            header       : true,
		            toolbar      : true,
		            footer       : true,
		            lineNumbers  : false,
		            selectColumn : true,
		            toolbarColumns : false
		        }, 
		        columns: [                
		            { field: 'ndg', caption: 'NDG', size: '8%' },
		            { field: 'naturaGiuridica', caption: 'N.G', size: '3%' },
		            { field: 'intestazione', caption: 'Intestazione', size: '30%' },
		            { field: 'dataNascita', caption: 'Data Nascita', size: '6%' },
		            { field: 'codiceFiscale', caption: 'Codice Fiscale', size: '10%' },
		            { field: 'residenza', caption: 'Residenza', size: '10%' },
		            { field: 'estinto', caption: 'Est.', size: '2%' },
		        ],
		        onClick:function(event){
		        	console.log(event);
		        } 
			});
        	w2ui['gridIntestaSettoristi'].load("myUrl");  

		    $('#popup').w2popup('open', {
			    title: "Prova",
			    showMax: true,
			    modal: true,
			    onOpen: function (event) {
			        event.onComplete = function (event) {
			            $('#w2ui-popup #gridIntesta').w2render('gridIntestaSettoristi');
			        };
			    }
			});
```

**Comment by spizzi77** [comment] 2016-05-05 13:25
Hi Again, just to inform you that i resolved the problem, but i must open the w2ui Grid inside a bootstrap modal and all is working fine, the search input it's perfect and all is quick to load, so the code became.Instead inside a popup it gives problem but for me it's ok load the grid inside a bootstrap modal.

`<div class="modal bs-example-modal-lg" id="modalIntestaSettoristi" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="myModalIntestaSettoristi">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title font13" style="text-align: center" id="myModalIntestaTitleSettoristi"><b> </b></h4>
      </div>
      <b><div class="modal-body" style="width: 100%; height: 700px;" id="contenutoModalIntestaSettoristi" align="center">
      </div></b>
      <div class="modal-footer">
      	<div align="center">
	        <button type="button" id="confInsertNdgIntesta" data-dismiss="modal" class="btn-x btn-success btn-xs">Salva</button>
	        <button type="button" id="delIInsertNdgIntesta" data-dismiss="modal" class="btn-x btn-danger btn-xs">Annulla</button>
        </div>
      </div>
    </div>
  </div>
</div>	


			$('#contenutoModalIntestaSettoristi').w2grid({
		        name: 'gridIntestaSettoristi',
		        msgNotJSON: 'Non ci sono validi risultati',
		        header : 'Risultati Ricerca',
		        show: {
		            header       : true,
		            toolbar      : true,
		            footer       : true,
		            lineNumbers  : false,
		            selectColumn : true,
		            toolbarColumns : false
		        }, 
		        columns: [                
		            { field: 'ndg', caption: 'NDG', size: '8%' },
		            { field: 'naturaGiuridica', caption: 'N.G', size: '3%' },
		            { field: 'intestazione', caption: 'Intestazione', size: '30%' },
		            { field: 'dataNascita', caption: 'Data Nascita', size: '6%' },
		            { field: 'codiceFiscale', caption: 'Codice Fiscale', size: '10%' },
		            { field: 'residenza', caption: 'Residenza', size: '10%' },
		            { field: 'estinto', caption: 'Est.', size: '2%' },
		        ],
		        onClick:function(event){
		        	console.log(event);
		        } 
			});
			
			url = w2ui['gridIntestaSettoristi'].load('/anagrafe/indice.php?azione=ricercaControlloIntestaSettoristi&intestazione='+intestazione+'&ndg='+ndg+'&timestamp='+timestamp);
			$('#contenutoModalIntestaSettoristi').load(url);
			$('#modalIntestaSettoristi').modal('show');`

**Comment by mrg2001** [comment] 2016-05-07 15:29
If problem is resolved, please close it. If not, please create a jsFiddle so that I can see what the problem is.

**Closed** 2016-05-07 17:02 UTC
