### ISSUE TITLE
Uncaught RangeError: Value , out of range for Number.prototype.toLocaleString

### ISSUE THREAD

**Issue by lukemcc20** [vitmalina/w2ui#2340] opened 2022-12-02 19:40 UTC
**Short description**

Im getting this error on Chrome Version 108.0.5359.72 

Its in regards to the w2ui form field type 'int'

Uncaught RangeError: Value , out of range for Number.prototype.toLocaleString options property useGrouping
    at Number.toLocaleString (<anonymous>)
    at Object.formatNumber (w2ui-1.5.min.js:2:7097)
    at n.format (w2ui-1.5.min.js:2:363955)
    at n.change (w2ui-1.5.min.js:2:364144)
    at n.init (w2ui-1.5.min.js:2:353506)
    at HTMLInputElement.<anonymous> (w2ui-1.5.min.js:2:347701)
    at Function.each (jquery.min.js:2:2715)
    at r.fn.init.each (jquery.min.js:2:1003)
    at b.fn.w2field (w2ui-1.5.min.js:2:347456)
    at h.refresh (w2ui-1.5.min.js:2:437657)
**What is current behavior**

...

**What is desired behaviour**

...

**Link to jsfidle/codepan with sample code**

...

**Steps to reproduce or sample** 

...

**Comment by CJayakumar** [comment] 2022-12-07 00:47
Hello Team,
We are also same issue with chrome (version 108.0.5359.73) and also Edge browser.
The issue occurs when we do the inline edit with the grid.

Uncaught RangeError: Value , out of range for Number.prototype.toLocaleString options property useGrouping
    at Number.toLocaleString (<anonymous>)
    at Object.formatNumber (w2ui.min.js:2:7097)
    at n.format (w2ui.min.js:2:363955)
    at n.change (w2ui.min.js:2:364144)
    at n.init (w2ui.min.js:2:353506)
    at HTMLInputElement.<anonymous> (w2ui.min.js:2:347575)
    at Function.each (jquery-3.5.1.js:381:19)
    at jQuery.fn.init.each (jquery-3.5.1.js:203:17)
    at b.fn.w2field (w2ui.min.js:2:347456)
    at w2grid.editField (w2ui.min.js:2:126678)
formatNumber @ w2ui.min.js:2
format @ w2ui.min.js:2
change @ w2ui.min.js:2
init @ w2ui.min.js:2
(anonymous) @ w2ui.min.js:2
each @ jquery-3.5.1.js:381
each @ jquery-3.5.1.js:203
b.fn.w2field @ w2ui.min.js:2
editField @ w2ui.min.js:2
dblClick @ w2ui.min.js:2
click @ w2ui.min.js:2
(anonymous) @ w2ui.min.js:2
dispatch @ jquery-3.5.1.js:5429
elemData.handle @ jquery-3.5.1.js:5233

**Comment by lukemcc20** [comment] 2022-12-07 01:00
Temporarily fixed issue by just modifying the w2ui.min.js

return parseFloat(e).toLocaleString(w2utils.settings.locale,s)}

--->
return parseFloat(e).toLocaleString()

**Comment by CJayakumar** [comment] 2022-12-07 01:31
Thank you, It's working fine.

**Comment by vitmalina** [comment] 2022-12-11 03:02
I think the error comes from this line https://github.com/vitmalina/w2ui/blob/master/src/w2utils.js#L474. I tried to play with it and cannot repeat it. What is the value you are formatting? And what is your current `w2utils.settings.lcoale`?

**Comment by alzambo** [comment] 2022-12-12 15:17
Hi, I have the same error in version 1.5.

At some  point `useGrouping` value become ',' (comma) instead of a boolean and it generates the error:
````
function formatNumber (val, fraction, useGrouping) {
    if (val == null || val === '' || typeof val === 'object') return '';
    var options = {
        minimumFractionDigits : fraction,
        maximumFractionDigits : fraction,
        useGrouping : useGrouping  <============= HERE 
    };
    if (fraction == null || fraction < 0) {
        options.minimumFractionDigits = 0;
        options.maximumFractionDigits = 20;
    }
    return parseFloat(val).toLocaleString(w2utils.settings.locale, options);
}
````
I've Temporarily fixed changing from `useGrouping: useGrouping` with `useGrouping: true` and it seems working.
`val` is 0.14 and `w2utils.settings.locale` is set to 'en-us'

Bye
Alex

**Comment by vitmalina** [comment] 2022-12-12 17:45
Are you sure it is the cause? I tried this in Chrome
```
Number(1.43e20).toLocaleString('en-US', { useGrouping: '' })
```
and it did not result in the error.

**Comment by quillaja** [comment] 2022-12-19 22:58
The problem is that `formatNumber()` is being passed "," (comma) for its `useGrouping` param. When this passed to `toLocaleString()` in `options`, it is **not** a valid value per [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#options). 

I'm using v1.5rc1 and suspect this bug has existed for a long time, but some recent Chrome update finally made `toLocaleString()` stop accepting the invalid input. Like @alzambo I just changed `formatNumber()` to ignore `useGrouping` and always use 'auto' in `options`.

The root cause might be that `w2utils.settings.groupSymbol` is set to "," on line 45 (in my working copy of 1.5rc1).
```javascript
var w2utils = (function ($) {
    var tmp = {}; // for some temp variables
    var obj = {
        version  : '1.5.RC1',
        settings : {
            "locale"            : "en-us",
            "dateFormat"        : "m/d/yyyy",
            "timeFormat"        : "hh:mi pm",
            "datetimeFormat"    : "m/d/yyyy|hh:mi pm",
            "currencyPrefix"    : "$",
            "currencySuffix"    : "",
            "currencyPrecision" : 2,
            "groupSymbol"       : ",",   // <--- perhaps this should be set to true or 'auto' ?
            "decimalSymbol"     : ".",
//....
```

**Comment by vitmalina** [comment] 2022-12-20 16:09
@quillaja, yes, I am aware that it was sending non boolean value for `useGrouping` when it only accepts booleans in new versions of Chrome. I have fixed it in both branches (1.5 and current master). Here the link to the fix: https://github.com/vitmalina/w2ui/commit/bbd96186d7eee7d755cf711ed801aa1143414339, Now, is the new updated versions work for you?

**Comment by quillaja** [comment] 2022-12-22 01:08
@vitmalina That seemed to work. Thank you.

**Comment by vitmalina** [comment] 2022-12-24 16:39
ok, then I am closing the issue

**Closed by vitmalina** 2022-12-24 16:39 UTC
