### ISSUE TITLE
Grid record total not incremented for remote grid; breaks non fixed display

### ISSUE THREAD

**Issue by sammyrc34** [vitmalina/w2ui#1541] opened 2017-03-04 07:55 UTC
The add() method should increment the record total for remote data grids, as it does for local grids.

When using a non fixed size grid with a URL, the grid sets an accumulative height ( 1 x row height per added row ) while adding rows. This occurs due to the height calculating height for less rows than exist.

You can observe this by calling add(), after which the id="grid_xxx_rec_bottom" TR element is being assigned a recordHeight inside scroll(). Once that happens, any call to refresh() will result in empty space being displayed beneath rows in the grid.

The work around for this is to manually increment the total after calling add().

I've attempted to create a fiddle, but I've been unable to mock the responses required to demonstrate a remote data store. And everything works as expected without a URL.

**Comment by mrg2001** [comment] 2017-03-05 00:44
For remote data source, after record is added, the grid should be refreshed. (who knows, may be someone else added a record too). Therefore, add() should not be used for remote. 

If you have a use case when it is needed, push to records array and increase total. Though, I think this use case is uncommon.

Since it is not a bug, closing.

**Closed by mrg2001** 2017-03-05 00:44 UTC

**Comment by sammyrc34** [comment] 2017-03-05 01:22
I assume you're referring to reload(), rather than refresh() which causes the broken display via the calculations in scroll().

Regardless, perhaps we'll have to agree to disagree in terms of add(). I could use your argument to say that delete(), or save() after an edit shouldn't be used for remote records either, as someone else may have altered the same record. 

If you will allow me, some advice as a former developer with large YUI datatables in multi-user development, the UI should not restrict, make decisions, or second guess what the remote store might or might not do. with data. If the developer wishes to enable editing of a remote store, then it is on them to ensure concurrency.
