### ISSUE TITLE
Grid: ERROR: Cannot add records without recid. (obj: grid)

### ISSUE THREAD

**Issue by petersirka** [vitmalina/w2ui#1273] opened 2016-06-21 11:34 UTC
Hi,
I found a problem with the Grid component. When I extend the `Array.prototype` about my method then the grid doesn't work.

Example:
```javascript
Array.prototype.myMethod = function() {
};

$(function () {
	$('#grid').w2grid({
		name: 'grid',
		header: 'List of Names',
		show: {
			toolbar: true,
			footer: true
		},
		searches: [
			{ field: 'lname', caption: 'Last Name', type: 'text' },
			{ field: 'fname', caption: 'First Name', type: 'text' },
			{ field: 'email', caption: 'Email', type: 'text' },
		],
		sortData: [{ field: 'recid', direction: 'ASC' }],
		columns: [
			{ field: 'recid', caption: 'ID', size: '50px', sortable: true, attr: 'align=center' },
			{ field: 'lname', caption: 'Last Name', size: '30%', sortable: true, resizable: true },
			{ field: 'fname', caption: 'First Name', size: '30%', sortable: true, resizable: true },
			{ field: 'email', caption: 'Email', size: '40%', sortable: true, resizable: true },
			{ field: 'sdate', caption: 'Start Date', size: '120px', sortable: true, resizable: true },
		],
		records: [
			{ recid: 1, fname: 'John', lname: 'doe', email: 'jdoe@gmail.com', sdate: '4/3/2012' },
			{ recid: 2, fname: 'Stuart', lname: 'Motzart', email: 'jdoe@gmail.com', sdate: '4/3/2012' },
			{ recid: 3, fname: 'Jin', lname: 'Franson', email: 'jdoe@gmail.com', sdate: '4/3/2012' },
			{ recid: 4, fname: 'Susan', lname: 'Ottie', email: 'jdoe@gmail.com', sdate: '4/3/2012' },
			{ recid: 5, fname: 'Kelly', lname: 'Silver', email: 'jdoe@gmail.com', sdate: '4/3/2012' },
			{ recid: 6, fname: 'Francis', lname: 'Gatos', email: 'jdoe@gmail.com', sdate: '4/3/2012' }
		]
	});
});
````

__w2ui-1.4.3.js__ line 1835:
```javascript
for (var r in records) {
}
```

Thank you!

**Comment by mpf82** [comment] 2016-06-21 13:59
Possible duplicate of https://github.com/vitmalina/w2ui/pull/873 / https://github.com/vitmalina/w2ui/issues/592

AFAIK, w2ui 1.5 has no issues with an extended `Array.prototype`.

**Comment by petersirka** [comment] 2016-06-21 14:04
Thank yoy and where can I download the new version?

**Comment by mrg2001** [comment] 2016-06-21 14:29
https://github.com/vitmalina/w2ui/blob/master/dist/w2ui.js
https://github.com/vitmalina/w2ui/blob/master/dist/w2ui.css

**Closed by mrg2001** 2016-06-21 14:29 UTC
