### ISSUE TITLE
how to proc horizontal scrollbar on w2ui sidebar?

### ISSUE THREAD

**Issue by mrjommer** [vitmalina/w2ui#1811] opened 2019-01-31 07:50 UTC
When a node name exceeds the horizontal size of the sidebar, it does not proc a horizontal scrollbar.

I need to use a horizontal scrollbar since I am using a hierarchical structure of the node list.

Please help me :(

**Comment by mpf82** [comment] 2021-04-26 15:28
Closing as duplicate of #919

**Closed by mpf82** 2021-04-26 15:28 UTC
Labels: Duplicate, Feature Request
