### ISSUE TITLE
Date & Time: demo popups are plain strange under FF

### ISSUE THREAD

**Issue by nexushoratio** [vitmalina/w2ui#1307] opened 2016-08-02 04:52 UTC
http://w2ui.com/web/demos/#!fields/fields-2

Happens with FF 47 but not with recent Chrome or Chromium.

First click on a field and the popup points to the right field.

Then start using TAB and Shift-TAB to navigate around.  The popup always points to the last field, not the field being edited.  When going from calendar to time fields, it renders time, but pointing to the calendar field.

![a](https://cloud.githubusercontent.com/assets/6006766/17317151/93ad1c60-582f-11e6-872c-8b40ad90e1d8.png)

When returning to a date field from a time field, all of the formating is lost in the rendering.

![b](https://cloud.githubusercontent.com/assets/6006766/17317167/b2689512-582f-11e6-8740-cc9a4e5e16de.png)

But visiting the next field renders properly (but still pointing to the wrong field).

![c](https://cloud.githubusercontent.com/assets/6006766/17317178/c9667a86-582f-11e6-980e-b640f4db00ec.png)

Unsure if related, but this is a HiDPI display (210x215 dpi).  Oh yeah, and Ubuntu.

**Comment by mpf82** [comment] 2016-08-05 08:32
I can reproduce this in FF 47.0 with w2ui 1.4

However, it seems to be fixed in w2ui 1.5 - http://jsfiddle.net/kjzyh43k/

**Comment by mrg2001** [comment] 2016-08-08 12:38
There will be no more updates in 1.4 branch and 1.5 will be out by the end of the summer. Since it is not a problem in 1.5.x, I am clothing it. If someone needs it, please fix in 1.4 branch. Thank you.

**Closed by mrg2001** 2016-08-08 12:38 UTC
