### ISSUE TITLE
formHTML not working

### ISSUE THREAD

**Issue by lukemcc20** [vitmalina/w2ui#2039] opened 2021-05-31 21:24 UTC
I have found an issue with the formHTML. Hoping someone can spread some light on the issue for me.

To see the example you can go directly to the provided demos

http://w2ui.com/web/demos/#/form/1

When rendering the form, it ignores any html provided and renders all the fields from the JavaScript. ( As seen in the above example when you got to jsfiddle for the example http://jsfiddle.net/api/post/jquery/2.1/ ).

***Needless to say this library has been amazing and I appreciate all the work that has been put into it.

**Comment by mpf82** [comment] 2021-06-01 13:31
You're right, the current master seems to ignore the HTML.

Current master: http://jsfiddle.net/tvL7493u/1/ 

w2ui 1.5 final: http://jsfiddle.net/tvL7493u/

**Comment by mpf82** [comment] 2021-09-14 06:42
This seems to be fixed, at least the fiddles are working fine now.

@lukemcc20 can you please confirm?

**Comment by mpf82** [comment] 2021-09-27 15:16
Closing issue as Fixed.

The issue can no longer be reproduced with the current master.

**Closed by mpf82** 2021-09-27 15:16 UTC
Labels: Fixed, Waiting For Reply, Bug, Reproducer: Present
