### ISSUE TITLE
ENUM - Dropdown list disappears in IE9+

### ISSUE THREAD

**Issue by ghost** [vitmalina/w2ui#1026] opened 2015-08-21 15:55 UTC
This was originally issue #550.    I do believe it was fixed, but it appears to be broken again.  This may also be related to issue #562.

When using an ENUM Multi-Select component, in IE, whenever the dropdown list appears, and you go to use the scroll bar (when there are hundreds of entries, scrolling is not really an option), the window disappears, and yes it appears that the component does reset itself.

**Comment by pelord** [comment] 2016-03-18 17:19
I have the same issue with IE9+ and w2ui-1.4.3.

**Comment by mrg2001** [comment] 2016-03-19 19:39
@ghost please specify version you used. Did you try nightly from dist folder?

**Comment by Dazorn96** [comment] 2017-10-24 09:03
Still having on IE 11.
Resolved with this fix:
- Removed `helper.find('input').on('blur')` on line **17188**
- Added this event to the **helper** after line **17208**:
`helper.on('blur', function (event) {
                $(obj.el).css('outline', 'none');
                $(this).find('input').val('');
                obj.refresh();
                $(obj.el).triggerHandler('blur');
                if (event.stopPropagation) event.stopPropagation(); else event.cancelBubble = true;
                if (pholder != null) $(obj.el).attr('placeholder', pholder);
            });`

**Comment by mpf82** [comment] 2017-10-24 09:49
@Dazorn96 can you create a fiddle to reproduce the problem?

I can not reproduce the problem(s) described in this issue by using http://w2ui.com/web/demos/#!fields/fields-4 or http://w2ui.com/web/demos/#!fields/fields-3 and IE11

**Comment by Dazorn96** [comment] 2017-10-24 09:54
@mpf82 i am using **w2ui-1.5.rc1.js**.
I have a _list_ type field, containing **400** items. When i want to scroll (**with the dialog scrollbar**), the input seems to lose focus and the dialog disappear.

**Comment by mpf82** [comment] 2017-10-24 11:42
@Dazorn96 I already understood that much.

The examples I have linked are also using w2ui-1.5.rc1.js - and specifically [this one](http://w2ui.com/web/demos/#!fields/fields-3) also has a list field with a scrollbar.

I still can not reproduce the problem you're mentioning in my Win7 with IE11 using the linked example and following the steps you have described.

That's why I asked if you can create and link a jsfiddle to reproduce the problem.

**Comment by Dazorn96** [comment] 2017-10-24 11:55
@mpf82 That's my page code:
https://gist.github.com/Dazorn96/10de7fea5a5e12e83f65e39ecd99a40f

**Comment by Dazorn96** [comment] 2017-10-27 07:35
Any updates?

**Comment by mpf82** [comment] 2017-10-27 07:38
@Dazorn96 Nope, I stopped looking into it, since you did not provide a fiddle and I could not reproduce it with the existing demo. Btw, did you try to reproduce it in the demo?

**Comment by mpf82** [comment] 2021-04-22 09:13
Closing issue: no response, no reproducer

**Closed by mpf82** 2021-04-22 09:13 UTC
