### ISSUE TITLE
BUG in w2grid select & scroll with jquery-3.5.1

### ISSUE THREAD

**Issue by Rimokas** [vitmalina/w2ui#1964] opened 2021-02-27 13:04 UTC
**Short description**
The latest w2ui, downloaded at 21 of February. W2grid infinite vertical scrolling and selection isn't working true with latest directed jquery-3.5.1. 

**Steps to reproduce or sample** 

Let say, that you have a grid with some pages, to use with scrolling to bottom.  
- Select first cell in the grid:

![image](https://user-images.githubusercontent.com/12154604/109387621-2195d200-790b-11eb-836f-641d90ae5f79.png)

- then scroll some to bottom and then return to the top : 

![image](https://user-images.githubusercontent.com/12154604/109387693-979a3900-790b-11eb-9581-f08fd0b1bfde.png)

The select cell remain in the same place, but frame of selection appears rather below. 

 - If to go to bottom and select the last record : 

![image](https://user-images.githubusercontent.com/12154604/109387848-548c9580-790c-11eb-9c01-383b4fbe5207.png)

differs selection field with cell in one row and scroll is the middle, not in bottom ... 

With jquery-3.1.1 all is working fine. 

...

**Comment by mpf82** [comment] 2021-03-09 15:17
Possibly a duplicate of #1890

**Closed** 2022-02-16 16:24 UTC
