### ISSUE TITLE
hex formatter?

### ISSUE THREAD

**Issue by susdu** [vitmalina/w2ui#1583] opened 2017-04-26 07:45 UTC
can I enter a number and get its hexadecimal representation using formatters in utils?

**Comment by mpf82** [comment] 2017-04-26 08:59
There's no hex formatter. There's only ``isHex()``. But you can certainly write your own formatter that will return a Hex value based on a Decimal input.

There's an example on how to create custom formatters in the docs: http://w2ui.com/web/docs/1.5/w2utils.formatters

**Comment by susdu** [comment] 2017-04-26 10:15
OK, I'll have a look, thanks

**Comment by mrg2001** [comment] 2017-04-26 13:41
you can write a custom formatter and add it to formatters. Since it is not a bug, I am closing it.

**Closed by mrg2001** 2017-04-26 13:41 UTC
