### ISSUE TITLE
Form's generateHTML doesn't seem to work with type='select'

### ISSUE THREAD

**Issue by psinigaglia** [vitmalina/w2ui#1225] opened 2016-04-30 18:50 UTC
Using a field with type='select' in a auto-generated form does not work properly: instead of a SELECT element, DOM contains an INPUT.
I patched this adding a line in function generateHTML:

if (field.type == 'select') input = '<select name="'+ field.name +'" '+ field.html.attr +'></select>';

before the line:

if (field.type == 'toggle')   input = '<input name="'+ field.name +'" type="checkbox" '+ field.html.attr +'

**Comment by mrg2001** [comment] 2016-05-01 14:58
I looked up some test scripts and it works just fine. Please specify version you used and provide JS fiddle to illustrate the problem

**Comment by mpf82** [comment] 2021-09-14 13:27
Closing issue: cannot reproduce.

Looks fine in the demos: http://w2ui.com/web/demos/#/form/3

Looks fine in a fiddle: https://jsfiddle.net/gjkd0a39/

**Closed by mpf82** 2021-09-14 13:27 UTC
