### ISSUE TITLE
Bug tabindex on the form with date fields

### ISSUE THREAD

**Issue by mendozada** [vitmalina/w2ui#1651] opened 2017-08-14 12:55 UTC
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

Hello, the bug happens when you are loading a form with dates, date fields are moved to the end of the list of indices,
Here is the example. 
https://jsfiddle.net/6go7556p/6/

I suggest if you can put a tabindex property in the field so the user can set it.

Thank you. regards

**Comment by mpf82** [comment] 2017-10-25 09:26
This is not a bug with w2ui, but you did add a batt ``attr`` property (you forgot the closing ``"``.

Updated fiddle: https://jsfiddle.net/6go7556p/7/

Please close this issue if your problem is solved.

**Closed** 2017-10-25 11:34 UTC
