### ISSUE TITLE
Dropdown inside w2grid's field not working in Firefox

### ISSUE THREAD

**Issue by microboy37** [vitmalina/w2ui#1639] opened 2017-07-13 09:34 UTC
[x ] bug report

* **What is the current behavior?**
<select> dropdown elements inside fields don't work with latest w2ui-1.5.rc1 in Firefox. Work well in IE and Chrome. Older w2grid 1.4 works OK in all browsers. Trying to change option in select element does not work.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**

Just provide the following JSON source to w2grid and try it in Firefox:
{"total":"1","records":[{"test":"<select><option value=\"1\">option 1</option><option value=\"2\">option 2</option><option value=\"3\">option 3</option></select>"}]}

* **Link to jsFiddle that demonstrates the problem:**

Please try it in Firefox:
http://jsfiddle.net/bxw1rk91/30/

**Comment by mpf82** [comment] 2021-04-23 08:55
I cannot reproduce the issue in Firefox, neither with your fiddle, nor with an updated fiddle that uses the current dist files: http://jsfiddle.net/cgvqkjdb/ 

Closing this issue as resolved.

**Closed by mpf82** 2021-04-23 08:55 UTC
