### ISSUE TITLE
[Feature Request] w2grid: Be capable of specifying different fields for simple-search and advanced-search.

### ISSUE THREAD

**Issue by thomasguo** [vitmalina/w2ui#1618] opened 2017-06-11 15:57 UTC
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
Currently developers can provides searches property for a grid to specifed what fields they want to search for. But they cannot specify different fields individually for the simple-search mode and advanced-search mode. For example, there is a grid that we want only 3 fields in the simple-search mode to do a fuzzy searching, meanwhile in advanced-search mode of this grid we would want 8 fields to do more complex and stricter filtering. 
 I notice that each search filter has a `simple: t/f` property, which can specify this field should show or not in simple-seach mode. But whether the field shows or not on the simple-search dropdown menu, its value always be submitted to server when triggering a 'All Fields' search. For end users this is very confusing  because they cannot see those extra search fields in the dropdown menu at all.

* **What is the expected behavior?**
If a search field's property 'simple' is set to false,  it only shows and takes effect in advance-search mode, not in the simple-search mode.

* **Other information**
I am using w2ui-1.5.rc1 version.

**Comment by LeicaHabit** [comment] 2017-06-11 15:59
This message was created automatically by mail delivery software at Junk Email Filter. 

The message from "thomasguo [Masked]" <FWD-737QTYSMENAIYCQANIQDDYCWEIMCQNTAFQQRQODCEA4QADHABT7QSOADQNADCX3KE4BV6ICMLIID2RDRIQSHE43CGUKS6ISMHC2CDGKYWAR3ATFZCFJEW5D43VJ7EKYTMORAOJKCVUSSAALQJBYACCAB5QAUYAD4ABGAC7BVJRYCOWBFLARHDSTBABQIEZFAAAQA====@opayq.com> is being returned by server opayq-outbound.junkemailfilter.com on Sun, 11 Jun 2017 08:58:52 -0700

A message that you sent could not be delivered to all of its recipients.

NOTE: And this is important - Junk Email Filter is a front end spam filtering service. We accept email for our customers, filter it, and pass the good email on. Sometimes when we forward email as good the server we forward to rejects it. Generally if you are getting this message it is because the server we forwarded to  * NOT JUNK EMAIL FILTER * has rejected the message.

If you see below the phrase "error from remote mail server" then it is the server who we are forwarding to, NOT US who is rejecting the email. Read the reason carefully and see if you can correct the cause of the rejection.

The following address(es) failed:

  marc@vlitos.net
    host vlitos.net [69.90.161.175]
    SMTP error from remote mail server after RCPT TO:<marc@vlitos.net>:
    554 Security failure

**Comment by thomasguo** [comment] 2017-06-13 01:29
Currently my workaround is extending w2grid and using the onSearch event handler. Like the following:
```
w2obj.grid.prototype.doBeforeSearch = function (event) {
    if(event.multi === false && event.searchField === 'all'){
        for(var i=0; i<this.searches.length; i++){
            var search = this.searches[i];
            if(search.simple === false) {
                event.searchData = event.searchData.filter(function(el){
                    return el.field !== search.field;
                });
            }
        }
    }
};
```
and 
```
$('#myGrid').w2grid({
    ...
   onSearch: function(event) {
       this.doBeforeSearch(event);
   },
   ...
});
```
This works.  But I hope it would be the default behavior of the Grid widget. 

BTW, w2ui is great work!   Thank you again!

**Comment by pidlo** [comment] 2017-06-13 05:46
Hello thomasguo 
I use ajax call for binding data in grid.
Prepare data before ajax call and do this like this..

```javascript
onSearch: function(event){
  //code before request call
  for (dataItem in event.searchData){
     //change data for server side
  }
  event.onComplete = function(){
      //do something after request call 
      console.log('on search complete');
      w2ui.AnotherGrid.clear();
  }
}
```

for me is this ok

**Comment by thomasguo** [comment] 2017-06-13 06:14
Hi pidlo,

Thanks for your help.  Yes we can prepare/modify the searchData before sending search request, just like your code as well as my code above show.  However, this requirement is so common that almost every grid with search will need to handle this.  So I prefer it would be handled by default  by framework, not by application developers.  I suppose that would make developers pleased. Hope I am not asking too much.   :-)

**Comment by mpf82** [comment] 2021-05-20 14:45
onSearch : function( event ) {
        if ( event.phase === 'before' ) {
            // search via simple search input field
            if ( event.searchField === "all" ) {
                // discard search items if they explicitely set search.simple = false
                var non_simple_fields = [];
                obj.searches.forEach( ( search_item ) => {
                    if ( search_item.simple === false ) {
                        non_simple_fields.push( search_item.field );
                    }
                } );
                if ( non_simple_fields.length ) {
                    event.searchData = event.searchData.filter( ( search_item ) => !non_simple_fields.includes( search_item.field ) );
                }
            }
            ....

I will discuss with @vitmalina if search.simple should also influence the initial creation of searchData

**Comment by vitmalina** [comment] 2021-05-21 17:11
The `simple` property is just an indicator wether search show up in simple search drop down. I updated documentation http://w2ui.com/web/docs/1.5/w2grid.searches to describe it.

Also, when user types text in search field and hits enter, if a search field is some field (not `All fields`), then it will construct a search request with that field only. In this case `simple` does not play a role. If it is `All fields` then depending on the entered value, it might submit some fields. For example, if you type `1` it will loop thru search fields and submit search for the fields that are `text`, `int`, `float`, etc. If you type `s` it will submit only for `int`

**Comment by vitmalina** [comment] 2021-05-21 17:12
The use of simple is correct. However in 2.0 there are plans to significantly change search, so the simple property might or might not stay. Because of this, I am closing this issue.

**Closed by vitmalina** 2021-05-21 17:12 UTC
Labels: Feature Request
