### ISSUE TITLE
grid issue with CSS:flex-grow (1.5)

### ISSUE THREAD

**Issue by marcoas** [vitmalina/w2ui#1299] opened 2016-07-22 10:13 UTC
Hi

I have a GRID, that work excellent...

But, within this code, the GRID is created, but not shown
Your HEIGHT remain in 0

Is FLEX-GROW a problem ?

```
<div class="container">
  <div class="divMENU">MENU GO HERE</div>
  <div class="principal">

     GRID GO HERE

</div>
```

  </div>

```
<style>
  .container { display: flex; flex-direction: column; height: 100%;  }
  .divMENU { height: 50px; }
  .principal { flex-grow: 1; }
</style>
```

**Comment by mpf82** [comment] 2021-04-22 12:58
Cannot reproduce: http://jsfiddle.net/e4z15236/

If you're still facing this issue, please provide a Fiddle/Bin/Pen to demonstrate the issue.

Closing for now.

**Closed by mpf82** 2021-04-22 12:58 UTC
Labels: Reproducer: Missing
