### ISSUE TITLE
getting JSON using URL

### ISSUE THREAD

**Issue by Scnck** [vitmalina/w2ui#1821] opened 2019-04-09 22:00 UTC
I created a quick ASP.net API to send JSON data to test the follow I can get it to work with IE but not able to get it to work in chrome.. I get the following errors

w2ui.min.js:5 ERROR: Server communication failed. 
   EXPECTED: {status: "success", total: 5, records: Array(1)} 
         OR: {status: "error", message: "error message"} 
   RECEIVED: undefined
   
   
   Access to XMLHttpRequest at 'https://localhost:44382/api/values' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

<script type="text/javascript">
$(function () {
    $('#grid').w2grid({ 
        name: 'grid', 
        header: 'List of Names',
        url: 'https://localhost:44382/api/values',
        method: 'GET', // need this to avoid 412 error on Safari
        show: {
            header         : true,
            toolbar     : true,
            footer        : true,
            lineNumbers    : true,
            selectColumn: true,
            expandColumn: true
        },        
        columns: [                
            { field: 'fname', caption: 'First Name', size: '30%' },
            { field: 'lname', caption: 'Last Name', size: '30%' },
            { field: 'email', caption: 'Email', size: '40%' },
            { field: 'sdate', caption: 'Start Date', size: '120px' }
        ],
        searches: [
            { type: 'int',  field: 'recid', caption: 'ID' },
            { type: 'text', field: 'fname', caption: 'First Name' },
            { type: 'text', field: 'lname', caption: 'Last Name' },
            { type: 'date', field: 'sdate', caption: 'Start Date' }
        ],
        onExpand: function (event) {
            $('#'+event.box_id).html('<div style="padding: 10px; height: 100px">Expanded content</div>');
        }
    });    
});
</script>

**Comment by ImAbhishekTomar** [comment] 2020-06-16 19:58
same issue i have facing. the service is working file and data format is correct but when i call this in grid using URL prop its showing same issue.

![issue3](https://user-images.githubusercontent.com/6933841/84822137-d9af7300-b039-11ea-9d29-13977a8e81c2.JPG)

**Comment by vitmalina** [comment] 2020-06-21 16:41
Thank you @ImAbhishekTomar for explanation. I reviewed the issue and it seems to be an issue with returned data, not the grid. Hence, closing it. If it is still an issue, please create a jsFiddle where the problem is illustrated. Thank you.

**Closed by vitmalina** 2020-06-21 16:41 UTC
