### ISSUE TITLE
[BUG]grid row ghost & ghost line position issue

### ISSUE THREAD

**Issue by tsubayan** [vitmalina/w2ui#2136] opened 2021-10-21 16:06 UTC
thanks you great work.
Grid row ghost & ghost_line position is not correct position when I selected a row which is scrolled position.
・reorderRows: true,
・w2ui-1.5 branch 
・jquery3.5
・firefox

**What is current behavior**
only use this sample with using w2ui-1.5 branch and change grid div height to 300px.
http://w2ui.com/web/demos/#/grid/26

1.scroll grid to bottom
2.select  a row  with reorder column then row ghost appear too bottom position.

I think scrollTop is not needed like bellow.

 ghost_line.css({
                           top  : pos.top + recs.scrollTop(),
                           left : mv.pos.left,
                           'border-top': '2px solid #769EFC'
                         });
ghost.css({
                 top  : mv.pos.top + mv.divY + recs.scrollTop(),
                  left : mv.pos.left
                 });
at w2grid.js mouseMove function.

**Comment by mpf82** [comment] 2021-11-25 10:59
I can confirm that this issue exists in the 1.5 branch: http://jsfiddle.net/6f03xmy5/

But it seems to be fixed in the current master (2.0): http://jsfiddle.net/6f03xmy5/1/

Thus I am closing this issue as fixed. 

If you want you can create a Pull Request that fixes the 1.5 branch.

**Closed by mpf82** 2021-11-25 10:59 UTC
Labels: Fixed, 1.5, Bug
