### ISSUE TITLE
inline grid selection bug

### ISSUE THREAD

**Issue by ooo4321** [vitmalina/w2ui#2148] opened 2021-11-22 03:27 UTC
![ezgif-4-ab06ba2661c4](https://user-images.githubusercontent.com/12015510/142796492-825b086b-9d74-4aad-9e21-201bf3183807.gif)

**Comment by mpf82** [comment] 2021-11-22 07:01
Can you plese provide a fiddle to demonstrate the issue?

My guess is you don't set a unique recid for the added records.

**Comment by ooo4321** [comment] 2021-11-22 07:54
thank you, found it it was because of the format of the response, it breaks if i send : 
["status"=>"success", "total"=>$model->count(), "records"=>$model->all()]
but it works ok if i send only : 
["status"=>"success", "records"=>$model->all()]

**Comment by mpf82** [comment] 2021-11-22 08:10
If you provide ``total`` it must represent the number of records available for the grid, not the number of records your current request returns.

E.g. your database contains 12,000 records and you are pulling them with limit 1,000, then ``total`` should always be ``12,000`` so the grid know that there are still records to pull from the server (during scrolling), until all 12,000 are present in the grid.

If you do not set total, or if you explicitely set total to ``-1``, then you are basically telling the grid that you don't know how many records are there to pull from the server and the grid will not perform any load requests during scrolling (unless you manually set ``grid.last.xhr_hasMore``, which is quite low-level).

If your grid has an url and you're "manually" adding records to the grid, you must update grid.total accordingly.

Only if your grid has no url set, then grid.add() will automaticall set ``this.total = this.records.length``.

**Comment by ooo4321** [comment] 2021-11-22 08:45
![bandicam 2021-11-22 08-33-43-640](https://user-images.githubusercontent.com/12015510/142830098-2833c4ac-9933-4c24-82e6-3e959b4b0b30.gif)

**Comment by ooo4321** [comment] 2021-11-22 08:46
This is another very strange misbehavior that i don't know what could cause it ... any idea ?

**Comment by mpf82** [comment] 2021-11-22 09:51
Unfortunately, this bug has been around for some time already, but so far noone provided a fix.

See:  [Fast scrolling using infinite Scroll returns blank div without records](https://github.com/vitmalina/w2ui/issues/1759)

Even in w2ui 2.0 you can reproduce it in the infinite scroll demo: http://localhost:8080/demos#/combo/5

**Comment by mpf82** [comment] 2021-11-22 09:56
I am closing this issue, because the initial issue turned out to be not a bug and the second issue is a duplicate.

**Closed by mpf82** 2021-11-22 09:56 UTC
Labels: Not A Bug

**Comment by ooo4321** [comment] 2021-11-22 10:05
thank u, great programming gg

**Comment by ooo4321** [comment] 2021-11-22 10:09
as a tweak that works for me i added :

**Comment by ooo4321** [comment] 2021-11-22 10:10
and it starts over without refresh
