### ISSUE TITLE
Tab with form 

### ISSUE THREAD

**Issue by redsofa** [vitmalina/w2ui#1169] opened 2016-02-23 19:04 UTC
Can someone point me to an example of creating a w2tabs element and adding form elements inside a tab ? 

Thanks in advance

**Comment by ppearson111** [comment] 2016-02-24 00:26
+1. Not a bug but just a request... a few more examples of tabs and various items rendered on tab-changes would be really helpful.  Like a layout, grid, from, etc. Thanks, Vitali!

**Comment by redsofa** [comment] 2016-02-24 14:45
For the time being, I am using jQuery UI element in the tabs. What I have now is working for my immediate tasks. These seem to be working so far but I would like to try some w2ui form elements at some point in the future.  Thank you for writing this awesome UI library. The layout manager is really awesome to work with.

**Comment by mrg2001** [comment] 2016-02-24 15:37
Form already has built in support for tabs. This is to make multi page forms. See http://w2ui.com/web/demos/#!forms/forms-5. In the similar way tabs can be added to a layout panel.

Note that tabs object is just a tabs strip, not content of the tab. You can add a div and then render form into it, see http://w2ui.com/web/demos/#!combo/combo-5

**Comment by mrg2001** [comment] 2016-02-24 15:37
As this is not a bug, I am closing this issue. You are welcome to continue conversation in it.

**Closed by mrg2001** 2016-02-24 15:37 UTC
