### ISSUE TITLE
grid can not sort by columns those with object value

### ISSUE THREAD

**Issue by hawkxu** [vitmalina/w2ui#1077] opened 2015-10-23 07:27 UTC
grid can not sort by columns those with object value, like column use list cell editor. click the column title will fire sort event (custom sort icon appeared), but the data didn't sort

**Comment by hkoster01** [comment] 2015-10-30 14:27
had same problem --

**Comment by vitmalina** [comment] 2015-11-01 00:15
I have just checked in current master, if I defined columns like
```js
            { field: 'name.first', caption: 'First Name', size: '100px', sortable: true, searchable1: true, resizable: true, editable: { type: 'text' },
                tooltip: 'Full Name', hidden1: true, info: true },
            { field: 'name.last', caption: 'Last Name', size: '100px', sortable: true, resizable: true,
```
and data record with
```js
            name: {
                first: fname[Math.floor(Math.random() * fname.length)],
                last: lname[Math.floor(Math.random() * lname.length)]
            },
```
it sorts just fine. 

Please give more details what the problem is.

**Comment by hawkxu** [comment] 2015-11-02 07:03
Please see this: http://plnkr.co/edit/lkR9bzqeVpBay4tbF7Kj?p=preview
After I click the column sex, custom sort icon appeared, but the data didn't sorted.

**Comment by hkoster01** [comment] 2015-11-05 17:37
I think this has to do with editability.  For me the problem was with editable fields, and for hawkxu also they are editable (selectable from a list).  I obviously don't want it to sort when I edit the field, but hitting the sort on the header should sort the fields that have already been edited

**Closed** 2016-05-21 22:33 UTC
