### ISSUE TITLE
[BUG] contextmenu - menuclick error 

### ISSUE THREAD

**Issue by mansurdegirmenci** [vitmalina/w2ui#2045] opened 2021-06-03 12:49 UTC
https://jsfiddle.net/mansurdegrmenci/4ftuovz1/11/

![resim](https://user-images.githubusercontent.com/38755096/120647048-d7306e00-c482-11eb-837f-89522ce2737a.png)

**Comment by mpf82** [comment] 2021-09-14 06:38
Closing as fixed, PR pending

**Closed by mpf82** 2021-09-14 06:38 UTC
Labels: Fixed, Bug, Reproducer: Present

**Comment by mansurdegirmenci** [comment] 2021-09-14 07:06
There is a problem in the contextmenu and the view.

Firefox:
![image](https://user-images.githubusercontent.com/38755096/133210949-cd1be094-c71b-4d6e-8892-a1def2f4c3be.png)
Chrome:
![image](https://user-images.githubusercontent.com/38755096/133211016-64abe86a-2f1c-4ec7-88aa-4c480a86bb98.png)

**Comment by mpf82** [comment] 2021-09-14 10:23
> 
> 
> There is a problem in the contextmenu and the view.
> 
> Firefox:
> ![image](https://user-images.githubusercontent.com/38755096/133210949-cd1be094-c71b-4d6e-8892-a1def2f4c3be.png)
> Chrome:
> ![image](https://user-images.githubusercontent.com/38755096/133211016-64abe86a-2f1c-4ec7-88aa-4c480a86bb98.png)

Probably a dupe of #2041 and/or #918

Side note: Please do not post follow-up issues in existing issues.

It's easier to answer (and to fix) issues if there is only one problem in the issue thread.

Same with your issue #2051 where the search list issue is fixed, but the backspace issue still exists - I cannot semi-close issues ;-)

**Comment by mansurdegirmenci** [comment] 2021-09-15 12:41
Since there is a situation related to the context menu, I wrote the problem here :) thank you, contextmenu click is working :)
