### ISSUE TITLE
Google Chrome problem

### ISSUE THREAD

**Issue by Dazorn96** [vitmalina/w2ui#1760] opened 2018-04-11 09:28 UTC
Hi all,
i am using `w2ui 1.5.rc1` with Google Chrome as main browser. 
Since last Chrome version update, currently i am on `65.0.3325.181 (Official Build) (64 bit)`, i noticed a bug (wrong element width) on w2toolbar menu-radio's w2overlay. I checked on Firefox `59.0.2 (64 bit)` and it works great.

**On Chrome (bugged?):**
![image](https://user-images.githubusercontent.com/10536581/38608242-174af6aa-3d7b-11e8-8bd2-cadb9f658700.png)
**On Firefox (correct):**
![image](https://user-images.githubusercontent.com/10536581/38608266-292581ec-3d7b-11e8-812f-0d90f8312876.png)

What's happening with Chrome?
Thank you

**Comment by vitmalina** [comment] 2018-04-11 15:37
I have checked demos, and all seems fine. http://w2ui.com/web/demos/#!toolbar/toolbar-6. Are you using standard menu or your own. Can you share code? Also, can you try with current version

https://raw.githubusercontent.com/vitmalina/w2ui/master/dist/w2ui.js
https://raw.githubusercontent.com/vitmalina/w2ui/master/dist/w2ui.css

**Comment by Dazorn96** [comment] 2018-04-11 15:47
I tried with current version, but the problem is the same... here it is my code:
```
toolbar: {
                        tooltip: 'bottom',
                        items: [
                            {
                                type: 'menu-radio', id: 'menu-line',
                                text: function (item) {
                                    return 'Linea: ' + item.selected;
                                },
                                selected: GetCurrentLinea().name,
                                items: []
                            },
                            {
                                type: 'menu-radio', id: 'menu-stato',
                                text: function (item) {
                                    return 'Stato: ' + item.selected;
                                },
                                selected: 'ALL',
                                items: [
                                    { id: 'ALL', text: 'Tutti gli stati' },
                                    { id: 'NEW', text: 'Nuovo' },
                                    { id: 'WIP', text: 'Work in progress' },
                                    { id: 'LAV', text: 'Lavorato' }
                                ]
                            },
                            { type: 'button', id: 'save-order', text: 'Salva ordine righe', tooltip: 'Salva l\'ordinamento attuale delle righe' },
                            { type: 'button', id: 'push-orders', text: 'Processa ordini', tooltip: 'Processa gli ordini selezionati da lavorare' }
                        ],
                        onClick: function (e) {
                            switch (e.target) {
                                case 'save-order':
                                    saveRowsOrder();
                                    break;
                                case 'push-orders':
                                    pushOrders();
                                    break;
                            }
                            e.onComplete = function (ev) {
                                if (ev.item.id === 'menu-line' || ev.item.id === 'menu-stato') {
                                    if (ev.subItem) getOrderList();
                                }
                            }
                        }
                    },
```

**Comment by vitmalina** [comment] 2018-04-12 00:38
I tried in my local setup and all seems fine. Here is screenshot

<img width="325" alt="screen shot 2018-04-11 at 5 35 29 pm" src="https://user-images.githubusercontent.com/561995/38650097-e51f66b4-3dae-11e8-811c-a84383d5ae7e.png">

Can you please create a jsFiddle where the problem is reproducible.

Also, I see some distortion in screenshot from FireFox. Do you add some custom css for this project. Could the problem be in that?

**Comment by Dazorn96** [comment] 2018-04-12 10:13
I can't add w2ui files to jsFiddle...
The problem is in the inline-style of the w2overlay box (applied from Javascript), then i don't think mine CSS file is the main problem.

**Comment by mpf82** [comment] 2018-04-12 12:08
@Dazorn96 You can easily create a jsfiddle from any w2ui demo.

Example:

1) Navigate to http://w2ui.com/web/demos/#!toolbar/toolbar-1 (or any other demo)
2) Click on the ``[Show Source Code]`` button below the demo
3) Click on the ``fiddle with code online`` link
4) Modify the fiddle and save it
5) Possible result: http://jsfiddle.net/028ns651/

**Comment by Dazorn96** [comment] 2018-04-12 12:53
http://jsfiddle.net/62ggjsmm/5/

**Comment by vitmalina** [comment] 2018-04-12 20:55
Here is where it works http://jsfiddle.net/62ggjsmm/11/

**Comment by mpf82** [comment] 2021-04-26 08:22
Closing issue: cannot be reproduced, as shown in the fiddle by @vitmalina 

@Dazorn96  If it's still not working for you, please create a new issue and provide a minimal example.

**Closed by mpf82** 2021-04-26 08:22 UTC
