### ISSUE TITLE
Form demo on IE9 throws error "AJAX Error 0:.."

### ISSUE THREAD

**Issue by from2day** [vitmalina/w2ui#406] opened 2014-02-06 12:01 UTC
When I access form at http://w2ui.com/web/demo/form with IE9 and hit save I get error:

```
AJAX Error 0: TypeError: Unable to get property 'addEventListener' of undefined or null reference
```

I have tried with IE9, IE11 with document mode IE9 - gives error.
With IE10+ the form works fine. 

I have tried with jQuery 1.11 and jQuery 2.0.3.

The documentation requirements shows IE9+, where lies the problem? 

Thanks.

**Comment by xycool** [comment] 2016-05-04 13:58
sorry for poor english.

like funkytaco post above, I have a same issue. 
I working on Windows 7, IE9 (not compatible mode), w2ui 1.4.3.js, jquery 1.12.1.js
when click form's save button, first display "saving..." and then no action.
i can see below message when press F12
ERROR: server communication failed. The server should return [object Object] OR [object Object] , instead the AJAX request produced this: [object Object] 
==> unable to get value of the property object is null or undefined
w2ui library doesn't support IE9 ?

**Comment by spizzi77** [comment] 2016-06-29 19:06
Hi, unfortunately i also must use IE9 in some projects, for company directive :) btw yes w2ui support IE9 with no problem, in this case IE9 doesn't recognize the addEventListener of the progress % state in Ajax call, this happen often with IE9, all days i'm fighting with differents problems of compatibility of IE9, because it doesn't recognize some portion of code if it's written in a modern way :) Like as for example some global declaration of variables.In this case, i just notified today that the problem is at line 13170 untill 13175 just the progress event, there are two solutions.Rewrite that portion of addEventListner in a way that IE9 likes or i think you can also comment that portion of code from 13170 at 13175 but DON'T COMMENT RETURN XHR :), Commenting that portion doesn't affect the right parse of the code just will not display the % state of the ajax call in save but it isn't a problem.You can use a ajax block ui and unblock ui for the wait.I commented that portion and it work perfectly also in IE9, i notified this problem only with the save of the form object.Hope this help.Bye

**Comment by mrg2001** [comment] 2016-07-04 17:17
Can you please fix it in /src/w2grid.js, test if it work for you and submit a pull request?

**Comment by spizzi77** [comment] 2016-07-04 21:58
Hi mrg, sincerely i'm new on github, i don't know how to move, btw the problem that i found was in w2form with IE9 when i send the request with the save method, it works perfectly in firefox but in IE9 it goes in fail in $.Ajax(ajaxOptions), i resolved commenting in this point....line 640, IE9 doesn't like this addEventListener but i speak for 1.4.3 version, sincerely i didn't test the last 1.5...I'm using 1.4.3 on my projects.

'''                        xhr.upload.addEventListener("progress", function(evt) {
                            if (evt.lengthComputable) {
                                var edata3 = obj.trigger({ phase: 'before', type: 'progress', total: evt.total, loaded: evt.loaded, originalEvent: evt });
                                if (edata3.isCancelled === true) return;
                                // default behavior
                                var percent = Math.round(evt.loaded / evt.total * 100);
                                $('#'+ obj.name + '_progress').text(''+ percent + '%');
                                // event after
                                obj.trigger($.extend(edata3, { phase: 'after' }));
                            }
}, false);
'''

**Comment by mpf82** [comment] 2021-09-17 08:16
Closing this issue, as there are no plans to support IE anymore.

**Closed by mpf82** 2021-09-17 08:16 UTC
