### ISSUE TITLE
Multi Search Box is closed when clicking on a date in type Date field

### ISSUE THREAD

**Issue by Snylten** [vitmalina/w2ui#1734] opened 2018-01-08 18:25 UTC
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
Multi Search Box is closed when a date is clicked (type=date). The box should be up until Search Button is clicked. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Link to jsFiddle that demonstrates the problem:**

* **Other information**

**Comment by mpf82** [comment] 2018-01-09 03:45
Duplicate of https://github.com/vitmalina/w2ui/issues/1616

**Comment by mpf82** [comment] 2021-04-23 14:04
Closing issue as resolved, since it's been fixed in PR #1751

**Closed by mpf82** 2021-04-23 14:04 UTC
Labels: Bug, Duplicate, Fixed
