### ISSUE TITLE
Grid related questions and fix requests

### ISSUE THREAD

**Issue by mansurdegirmenci** [vitmalina/w2ui#2113] opened 2021-09-28 16:14 UTC
1- Have you considered changing the "scroll"? Is it possible to do something nice like on youtube or is it a waste of time?
![image](https://user-images.githubusercontent.com/38755096/135123123-aedb7b99-90c9-4ddf-b8a2-34f65575b44c.png)

2-  "value" in "w2ui.grid1.last._edit" is empty. Is there an error or is the last edited data displayed?
![image](https://user-images.githubusercontent.com/38755096/135123934-e9dfa6d5-0365-41b3-81d6-66c8e8900c9a.png)

3- Imagine that many people are using the same list. When one changes the list, I want the other to change at the same time. I did it with web socket, it works, but when the user is editing the list, that is, when editmode is open, the data is not updated. Is it possible to turn off edit mode as "progrability"?

4- There is "info buble", a nice feature, thank you for making it available. Have a "note" field. Note fields are too long to be displayed on the "grid". I thought of something like this. if there is "note" I want to show "info buble" in my line, otherwise I don't want to show it. As far as I understand from the examples, it is not possible to pass empty.

thanks for everything

**Comment by mpf82** [comment] 2021-09-29 00:26
> 1- Have you considered changing the "scroll"? Is it possible to do something nice like on youtube or is it a waste of time?

Related duplicates: #3 (though it seems no longer be on the w2ui 2.0 roadmap?), #347 (open FR), #995 (seems someone got it working already)

> 2- "value" in "w2ui.grid1.last._edit" is empty. Is there an error or is the last edited data displayed?

editField() is pretty much always caled with third param (value) = null - not sure it this needs to be changed

> Is it possible to turn off edit mode as "progrability"?

?

> 4- There is "info buble", ... if there is "note" I want to show "info buble" in my line ... As far as I understand from the examples, it is not possible

Yes, that's not possible with info bubble. But you can define your own column renderer. The column renderer gets passed the whole record, so you can decide based on your record.note field if you want to render your own info bubble or not. Related demo: http://w2ui.com/web/demos/#/grid/29

**Comment by vitmalina** [comment] 2021-09-29 01:46
My two cents
1. Agree with @mpf82 
2. any `.last` considered temporary or internal. You should not rely on them
3. there are `onEdit` and `onChange` events, they should be enough to get you any custom behavior. I too do not understand you euqstion here
4. ditto @mpf82 , also see http://w2ui.com/web/demos/#/combo/13

**Comment by vitmalina** [comment] 2021-09-29 01:47
As this is not a bug report, nor a clear feature request, I propose to close it. You can continue the discussion if you like, for informational purposes.

**Closed by vitmalina** 2021-09-29 01:47 UTC

**Comment by mansurdegirmenci** [comment] 2021-09-29 08:06
3. I expressed it wrong, let me say: How should I do when the edited row is changed by another user. I'm using the "grid.set()" method, it doesn't work :)
![Animation](https://user-images.githubusercontent.com/38755096/135220440-73193dcf-7c1c-4ba1-8222-7fa774189f52.gif)

**Comment by mpf82** [comment] 2021-09-29 10:10
If the field is changed, the displayed value is taken from ``record.w2ui.changes[field_name]``, so you would have to update that, too.

Or you remove ``record.w2ui.changes[field_name]`` (or all changes, not just for a specific field) if the record has been changed by some other user - depends on your requirements.

**Comment by mansurdegirmenci** [comment] 2021-10-05 19:11
problem removing rows from grid.

![Animation10](https://user-images.githubusercontent.com/38755096/136087566-6336f927-3f6e-48c8-811c-4ee9578eb861.gif)
