### ISSUE TITLE
Check All grid checkbox based on button click

### ISSUE THREAD

**Issue by jackryu** [vitmalina/w2ui#1462] opened 2017-01-10 15:49 UTC
Hello Team,
I have one grid column type check box, I need check and uncheck all check box based on button click it is possible using any w2ui grid function if possible please suggest this is critical for me.

**Comment by spizzi77** [comment] 2017-01-11 10:53
Sincerely i don't understand which button click?The button inside the toolbar?

**Comment by jackryu** [comment] 2017-01-17 16:15
_Yes I am create on button inside the toolbar._

**Comment by thipages** [comment] 2017-01-17 16:21
This may help : [grid demo](http://w2ui.com/web/demos/#!grid/grid-10)

**Comment by jackryu** [comment] 2017-02-20 15:07
![need select all checkbox](https://cloud.githubusercontent.com/assets/6933841/23130438/622ebd2a-f7ac-11e6-95b7-629b31a03010.jpg)

**I need this.**

**Comment by jackryu** [comment] 2017-02-21 22:27
@taipags

**Comment by vitmalina** [comment] 2017-02-21 23:26
duplicate of https://github.com/vitmalina/w2ui/issues/1526

**Closed by vitmalina** 2017-02-21 23:26 UTC
