### ISSUE TITLE
Grid "get" doesn't work in 1.5 "release" version

### ISSUE THREAD

**Issue by elaw01887** [vitmalina/w2ui#1997] opened 2021-04-13 20:01 UTC
**Short description**
The "get" ("load" function) of the grid doesn't seem to be working right.

**What is current behavior**
Per the documentation and recent versions, part of the payload sent to the server when the grid loads is a "cmd" which in the case of loading records would be "get".  With the 1.5 version I just downloaded from w2ui.com, the "cmd" parameter is not sent:
![W2ui grid get](https://user-images.githubusercontent.com/14806224/114613192-ff64d300-9c70-11eb-915e-b61243818e68.PNG)
Comparing w2ui-1.5.js to w2ui.1.5.rc1.js, it appears the whole "request" function has been rewritten so it's hard to tell if this new behavior is intentional or not.

**What is desired behavior**
Either fix the documentation or the code!

**Link to jsfidle/codepan with sample code**
...

**Steps to reproduce or sample** 
Write a simple web page using the grid, using the grid "load" function to pull data from a server.

**Comment by mpf82** [comment] 2021-04-13 22:40
Duplicate of https://github.com/vitmalina/w2ui/issues/1869 and https://github.com/vitmalina/w2ui/issues/1837

**Comment by elaw01887** [comment] 2021-04-14 19:08
Ah... sorry about that!  I'd looked through the list to see if this was already discussed but didn't see those.

As someone posted under one of the other entries, this is a real PITA when using the JSON datatype, and in my opinion serves no useful purpose.  I use the grid in about 85 places in the intranet site I maintain, and changing the code to accommodate this and other arbitrary changes (like renaming of parameters) is going to mean a ton of work for no good reason.  :^(

**Comment by mpf82** [comment] 2021-04-14 20:44
Well, that someone was me, but in the end, the fix was easy enough in our Python backend:

    cmd = params.get("cmd", params.get("action", "get")).lower()

But then again, we're using a single URL, so we only had to change this in one place to make it work for all our some-hundred grids. If you're working with different URLs for each grid, I can understand that making such a change in 85 places is annoying, especially since it's not (yet) well documented.

**Comment by vitmalina** [comment] 2021-04-14 21:00
Automation, guys :). I love when I can write a small script that makes me feel like I am an amazing engineer :). I am set to do some major updates to documentation of 1.5, so that it would be all current. Will update grid as well. If anyone is willing so donate some time for documentation update, would be great. All changes are not in comments at the top of the files, which is just a reference what needs to be updated in documentation. ))

**Comment by vitmalina** [comment] 2021-04-15 17:11
I just thought you can add extend grid's prototype and it should allow you to do it with one line of cone. Something like this
```
w2obj.grid.prototype.postData = { cmd: 'get' }
```
See, http://w2ui.com/web/docs/1.5/utils

**Comment by vitmalina** [comment] 2021-04-16 23:31
Documentation got updated, http://w2ui.com/web/docs/1.5/grid

**Closed by vitmalina** 2021-04-16 23:31 UTC
