### ISSUE TITLE
List overlay not rendering in 1.5

### ISSUE THREAD

**Issue by rubennavarroc** [vitmalina/w2ui#1375] opened 2016-11-08 07:41 UTC
Hello, I am using version 1.5 rc1.

I have a list field with more than 100 items. 

The problem is that, when I click the field to show the list of items, it only works if there's a scrollbar in the window, otherwise the overlay is not even inserted.
If there's a scrollbar in the window, it renders the overlay on top of the input.

The options object for the list field is like the following: 

`options: {
                            items: items_list,
                            openOnFocus: true,
                            minLength: 0,
                            match           : 'contains', 
                            markSearch: true
                        }`
In the following images I try to show the scenario. Inside the yellow square is the list field that is being clicked. Inside the green square is the place where the browser's scroll is supposed to be (or not).

![screenshot_5](https://cloud.githubusercontent.com/assets/6191954/20091052/37d6eaaa-a556-11e6-978d-451b07f12591.png)
(In this image I show how the overlay is shown when there's a scrollbar in the window. (e.g. when the browser's size is small enough)

![screenshot_3](https://cloud.githubusercontent.com/assets/6191954/20091063/61c67326-a556-11e6-8372-4d7bdfb2713b.png)
(In this image I show how the overlay is not shown (not even rendered) if there's not a scrollbar)

![screenshot_4](https://cloud.githubusercontent.com/assets/6191954/20091094/8d6ada26-a556-11e6-88bc-488582665c45.png)
(In this image I show how the overlay is shown if there's not a scrollbar but only when typing text)

**Comment by mpf82** [comment] 2016-11-08 08:00
I could not reproduce your issue, neither in my working environment, nor in a fiddle:

https://jsfiddle.net/voowqjae/

Tested on Win7 with Firefox and Chrome - both times with a browser window high enough to fit the overlay and with a smaller window that makes the overlay shrink to the maximum available height.

**Comment by rubennavarroc** [comment] 2016-11-08 08:52
Thank you for your reply. I was able to reproduce the issue here: http://jsfiddle.net/dg4wo217/

**Comment by mpf82** [comment] 2016-11-08 09:08
I could still not reproduce the problem with the [fiddle](http://jsfiddle.net/dg4wo217/) you provided.

The list opens for me fine whenever I click it, even if there's no scrollbar.

![2016-11-08 10_06_02-edit fiddle - jsfiddle](https://cloud.githubusercontent.com/assets/10152404/20092997/1c02ed20-a59b-11e6-97e6-be67bd114811.png)

**Comment by rubennavarroc** [comment] 2016-11-08 09:10
Okey can you check this one http://jsfiddle.net/6yqfpykz/

**Comment by mpf82** [comment] 2016-11-08 09:24
Now I can confirm the behaviour you're describing.

I've updated the fiddle to reduce the required code to reproduce the issue: http://jsfiddle.net/6yqfpykz/1/

Even though the first div is empty, it seems to be the culprit.

**Comment by rubennavarroc** [comment] 2016-11-08 09:27
If you place the div on the right instead of the left, then it works well.

**Comment by rubennavarroc** [comment] 2016-11-10 21:13
I can also notice that it also fails when the input is inside a "container" div.

**Comment by rubennavarroc** [comment] 2016-11-15 04:42
In case anybody has this same issue and wants a workaround here it is:
Just add height: 101vh !important; to your body.

**Comment by mpf82** [comment] 2021-04-22 12:40
Closing issue: resolved

**Closed by mpf82** 2021-04-22 12:40 UTC
