### ISSUE TITLE
Tree Grid breaks if we change recid to something else

### ISSUE THREAD

**Issue by peterchavasse** [vitmalina/w2ui#1908] opened 2020-06-10 00:18 UTC
## Short description
Chrome breaks (oh snap!) if we expand then collapse a tree row when: 
 >>  a) there are a large number of records (200?)
   b) we change the recid field to something else

## What is current behavior
>>  1) set recid to use some other field.  
>>  2) expand a row (with a large number of children)
 >> 3) try to collapse the row.

result -> Chrome crashes

If we use recid then it works fine

## What is desired behaviour
It should work with recid field changed to something else

## Link to jsfidle/codepan with sample code
FAILS:     [http://jsfiddle.net/32Ljbomz/1/](http://jsfiddle.net/32Ljbomz/1/)
WORKS: [http://jsfiddle.net/32Ljbomz/2/](http://jsfiddle.net/32Ljbomz/2/)

## Steps to reproduce or sample 
Expand Motzart -> Franson -> Franson

Try to collapse - using recid works, using id fails.

**Comment by peterchavasse** [comment] 2020-06-10 00:31
here is an example where recid has been changed, but it works (I have reduced the number of records)

[http://jsfiddle.net/32Ljbomz/3/](http://jsfiddle.net/32Ljbomz/3/)

**Comment by antoninmeunier** [comment] 2020-12-02 12:07
Hello @peterchavasse.

I have the same problem when expanding/collapsing rows with large number of records, did you find a solution?

**Comment by vitmalina** [comment] 2020-12-04 16:04
I tried all 3 jsfiddles and all 3 seem to work. I expanded all possible nested items. When it fails, what exactly happens. Also, I did not understand what it means "fails". Also, recid must be unique. If it is not unique, it will not select record right.

**Comment by antoninmeunier** [comment] 2020-12-04 16:46
Hello @vitmalina 
Thanks for replying.

I will try to be more clear : if you try on the first fiddle to expand and collapse the node Motzart->Franson->Franson your navigator will crash (out of memory). It might be due to the fact that ids are not unique in this case as you mentionned.

However, I got the exact same problem on my app (I use the last version of your library) on big nodes ( +-500 entry and deeply nested). The navigator falls into out of memory when you try to collapse nodes with lot of datas. All my ids are different in my case.

I finally got access to the entry flux and changing "id" into "recid" solved my problem.

I hope it's more clear. 

Great work on this library!

**Comment by peterchavasse** [comment] 2020-12-04 17:17
Hi,

Sorry for late reply.  The failure was chrome crashing - with oh, Snap! message. Like antoninmeunier, I was also able to change "id" in to "recid" and all was well.

Having said that, I see the jsfiddles are both working - I am wondering if it was a specific issue in a nightly build some time ago, which has been fixed. @antoninmeunier  - are you using the latest nightly or even official 1.5?

Anyway @vitmalina , great to know you are still looking - the grid control is amazing!  I see 1.5 is now official - that is good news.

Have you got a roadmap of new features/ideas?

**Comment by antoninmeunier** [comment] 2020-12-07 09:12
Hello,

My version is w2ui 1.5.x (nightly). This is a build downloaded from the website 4 months ago I would say

**Comment by vitmalina** [comment] 2020-12-07 16:24
@peterchavasse new features mostly around new things that JS/CSS can do now. I want to rewrite with `let` `arrorw functions` `flex grid`. Some styling visual updates. Will drop support for old browsers. I don't think there will be too many "new" features, just making current features use modern JS/CSS

**Comment by vitmalina** [comment] 2020-12-07 16:25
Since looks like it is resolved. I am closing the issue

**Comment by mpf82** [comment] 2021-05-12 16:12
Cannot reproduce if I provide unique ids for the children: http://jsfiddle.net/3sf1wknq/

Closing issue. Feel free to re-open if the issue still exists.

**Closed by mpf82** 2021-05-12 16:12 UTC
