### ISSUE TITLE
double request when delete rows for grid, how to fix it?

### ISSUE THREAD

**Issue by namewhat** [vitmalina/w2ui#1880] opened 2020-02-07 02:38 UTC
when the 'url' is set of a grid, then I trigger the delete event, requesting sent twice. I just want request one, how to fix it?

**Comment by mdavis1960** [comment] 2020-03-04 14:12
I can't reproduce this.  How are you triggering the delete event?

**Comment by vitmalina** [comment] 2020-03-04 16:37
I cannot reproduce it eaither

**Comment by namewhat** [comment] 2020-03-24 07:05
> 
> 
> I can't reproduce this. How are you triggering the delete event?
some action like this `document.getElementById('file').click()`, after tragger it,I found that the log of back-end show two request message about it, whatever the event is "onAdd","onRequest" or "onDelete"

**Comment by mpf82** [comment] 2021-04-28 09:16
Can you please provide a Fiddle/Bin/Pen to demonstrate the issue?

**Comment by mpf82** [comment] 2021-06-18 08:13
Closing issue: cannot reproduce; no reproducer provided

**Closed by mpf82** 2021-06-18 08:13 UTC
Labels: Reproducer: Missing, Waiting For Reply
