### ISSUE TITLE
[Question] Angularjs and w2ui

### ISSUE THREAD

**Issue by Tooa** [vitmalina/w2ui#1005] opened 2015-07-27 10:58 UTC
Hi,
w2ui provides everything I need for multiple resizable pane views. In my project I use Angularjs with the [ui-router](https://github.com/angular-ui/ui-router) and I wonder, how to combine these two technology stacks. 

Ui-router supports [multiple views](https://github.com/angular-ui/ui-router/wiki/Multiple-Named-Views) in the following fashion:

    
        <body>
            <div ui-view="filters"></div>
            <div ui-view="tabledata"></div>
            <div ui-view="graph"></div>
        </body>

W2ui however, requires just <b>one</b> div, where the rest comes from Javascript.
`<div id="layout" style="width: 100%; height: 400px;"></div> ...`

How to add the named `ui-view` tag with w2ui? 

Regards Uli

**Comment by vitmalina** [comment] 2015-08-10 00:06
I have implemented basic Angular controllers for w2ui and it seems to be working fine, however, I am not sure I can help you with more advanced usage. I hope some one from the community can help you with it.

**Comment by tarzasai** [comment] 2015-11-19 11:11
I wonder if is possible to use a directive to render a w2ui grid column, like this:
```javascript
    $('#grid').w2grid({ 
        name: 'grid', 
        columns: [            
            { field: 'fname', caption: 'Full Name', size: '200px',
                render: function (record, index, column_index) {
                    return '<my-directive/>';
                } 
            },
```
If yes, how can I get the row data inside the directive? Should I explicit put it in the scope (i.e. `<my-directive=record/>`) or what?

**Comment by vitmalina** [comment] 2015-11-21 20:14
Appreciate the discussion, but I'd like to reserve issues for bug reports. Since, it is not a bug, I am closing it. You are welcome continue the disucssion.

**Closed by vitmalina** 2015-11-21 20:14 UTC
