### ISSUE TITLE
selecting multiple rows in subgrid also selecting the rows with same recid in parent grid

### ISSUE THREAD

**Issue by dalsword** [vitmalina/w2ui#1275] opened 2016-06-23 07:18 UTC
http://w2ui.com/web/demos/#!grid/grid-7

Please expand the first row in the above example and select the rows in sub grid and you'll see that the rows with the same recid in the parent grid are also selected...

![select](https://cloud.githubusercontent.com/assets/10339831/16294837/c347adc8-392b-11e6-9b4b-6a60355d8162.PNG)

**Comment by mrg2001** [comment] 2016-06-27 06:42
Working fine for me

<img width="1219" alt="screen shot 2016-06-26 at 11 42 01 pm" src="https://cloud.githubusercontent.com/assets/1964803/16370835/9b797c1c-3bf7-11e6-8125-5f0cadf8f764.png">

**Comment by mrg2001** [comment] 2016-06-27 06:43
Pleas note that in 1.5 it was refactored quite a bit. So, I am closing it as it unlikely to be looked at in 1.4 branch.

**Closed by mrg2001** 2016-06-27 06:43 UTC

**Comment by mpf82** [comment] 2016-06-27 07:38
@mrg2001 To reproduce this in the demo, you have to "drag-select" the records, by clicking on the "Gatos" entry, keep the mouse button down and move the cursor down over the Welldo / Bahh.

I can also reproduce this in 1.5 - though I know that you've already said that sub-grids will no longer officially be supported, in favor of the new tree-grids.

**Comment by mrg2001** [comment] 2016-07-04 17:23
Can you reproduce it in 1.5 with tree-like grid? If I remember correctly, I have completely removed old nested grids when implemented tree like grids.

**Comment by mpf82** [comment] 2016-07-04 21:32
I haven't tested this with tree grids.

Fortunately, nested sub-grids still work in 1.5 (we need this to display relations of different DB tables, so tree-like grids are not an option for us, because the fields of the different tables do not match).

I really hope, this feature will never be completely removed from w2grid :)

**Comment by mrg2001** [comment] 2016-07-11 17:00
I fixed the issue in 1.5 branch. I have tried to apply the same in 1.4 branch, but it breaks other functionality, keyboard navigation is not working for example.

Indeed, this functionality works in 1.5 too, I remember a bit more about it. I 1.4 keyboard navigation will take you into sub grid if you click up/down keys. This is what was removed in 1.5. I think that expandable grids will stay, as there is a use case when you need it, for example displaying some text below the record when record is expanded. However, grid inside a grid is what I did not really like because it becomes messy. You are welcome to use it (if it works for you).

**Comment by dalsword** [comment] 2016-07-11 17:13
what do you suggest instead of expandable sub-grid. Is there any replacement in 1.5 release?

**Comment by mrg2001** [comment] 2016-07-11 17:49
Tree like grids. There is already a demo for it in the master repo. Here is link if
```
/demos/#!grid/grid-7
```

**Comment by dalsword** [comment] 2016-07-12 04:42
hmm... I was referring to the same example when I said "expandable sub-grid". I am a little bit confused, what exactly nested sub-grid is? Can you also provide a link?
