### ISSUE TITLE
Strange row style behavior after sorting

### ISSUE THREAD

**Issue by atitoff** [vitmalina/w2ui#1813] opened 2019-02-13 08:44 UTC
insert array records
```javascript
records = [
  {
    "w2ui": {
      "style": "background-color: #C2F5B4"
    },
    "recid": 222,
    "uid": 3009628363,
    "last_hb": "0:00:11",
    "status": 1
  },
  {
    "w2ui": {
      "style": "background-color: #C2F5B4"
    },
    "recid": 223,
    "uid": 2142734313,
    "last_hb": "0:00:08",
    "status": 2
  },
  {
    "recid": 2042,
    "uid": "",
    "last_hb": "",
    "status": 0
  },
  {
    "recid": 2043,
    "uid": "",
    "last_hb": "",
    "status": 0
  },
  {
    "recid": 2044,
    "uid": "",
    "last_hb": "",
    "status": 0
  },
  {
    "recid": 2045,
    "uid": "",
    "last_hb": "",
    "status": 0
  }
];
this.grid_can_modules.records = records;
```
All right, two row turned green.
After clicking the sort, all rows are green!

**Comment by mpf82** [comment] 2019-02-13 13:27
Cannot reproduce: http://jsfiddle.net/gcbL8um9/

Please create a minimal fiddle yourself next time.

To create a fiddle, you could start with any of the grid demos, e.g. http://w2ui.com/web/demos/#!grid/grid-1 

Then click on the button **[Show Source Code]** and then click **fiddle with code online**, or simply create a fiddle from scratch.

**Comment by atitoff** [comment] 2019-02-13 17:04
Downloaded the latest version w2ui, all works correctly. Thank!

**Comment by lhaig** [comment] 2019-03-28 12:40
@atitoff close the issue if you are happy with your answer please :-)

**Comment by mpf82** [comment] 2021-04-26 15:34
Closing issue: resolved

**Closed by mpf82** 2021-04-26 15:34 UTC
