### ISSUE TITLE
Search date format not respected with "between" matcher

### ISSUE THREAD

**Issue by BBE78** [vitmalina/w2ui#1278] opened 2016-06-25 17:02 UTC
Date format specified in options in not respected when switching from "is" matcher to "between" matcher.
Set 'yyyy-mm-dd' but default (I assume) is set. See attached capture.
![date-format-search-issue](https://cloud.githubusercontent.com/assets/5666567/16358019/19dd6128-3b07-11e6-82cc-ddaef6c3d68d.png)

**Comment by mpf82** [comment] 2016-06-26 22:39
Can you create a [fiddle](http://jsfiddle.net/) to reproduce the problem?

**Comment by BBE78** [comment] 2016-06-27 17:42
Done: [Fiddle](http://jsfiddle.net/BBe78/tk8pch7r/6/)

1. Click on "Search" button on the toolbar, the advanced search dialog is displayed, and the "Start Date" format is correct.
2. Click on the matcher to switch to "between" --> the input format is not correct

**Comment by mpf82** [comment] 2016-06-27 19:01
This seems to be fixed in 1.5, see http://jsfiddle.net/tk8pch7r/7/

**Comment by BBE78** [comment] 2016-06-27 20:57
It seems... In a future 1.5?

**Comment by mpf82** [comment] 2016-06-28 07:12
w2ui 1.5 is the current master in this github project, it's just not released as "stable", but it's stable enough for productive use. The only downside is, hat there are minor differences to the current online documentation, due to new or changed features - and sub-grids are no longer officially supported, in favor of a new tree-grid view. 

You can use the files in the [dist](https://github.com/vitmalina/w2ui/tree/master/dist) folder, or [download](https://github.com/vitmalina/w2ui/archive/master.zip) the whole project.

**Comment by BBE78** [comment] 2016-06-28 19:46
Thank you for your feedback, I'll wait the official/stable release because I'm using the sub-grid feature... So it will useful to have the associated documentation available...
Do you have an idea of a release date ?

**Comment by mpf82** [comment] 2016-06-28 20:13
>  Do you have an idea of a release date ?

https://github.com/vitmalina/w2ui/issues/1272

Quote from @mrg2001 

> Need to finish docs and demos. If you can please help. The source code itself is stable. The docs and demos have been done for some components, but not all yet.

> If you open any core file in /src directory, in the top of the file you will see comments of what new in 1.5. This needs to be verified in docs and demos that is is described. Thanks.

**Comment by mrg2001** [comment] 2016-06-29 16:20
Guys, I promise to release 1.5 this summer.

**Closed by mrg2001** 2016-06-29 16:20 UTC
