### ISSUE TITLE
fa- icons don't show up

### ISSUE THREAD

**Issue by ruttydm** [vitmalina/w2ui#1444] opened 2017-01-03 17:43 UTC
Currently i have the following code:

```
var pstyle = 'border: 2px solid #dfdfdf; padding: 5px;';
// first define a layout
$('#layout').w2layout({
    name: 'layout',
    panels: [
        { type: 'top', size: 45, style: pstyle},
        { type: 'left', size: 200, resizable: true, style: pstyle},
        { type: 'main', style: pstyle }
    ]
});

// then define the sidebar
w2ui['layout'].content('left', $().w2sidebar({
	name: 'sidebar',
	img: null,
	nodes: [
		{ id: 'level-1', text: 'Level 1', img: 'icon-folder', expanded: true, group: true,
		  nodes: [ { id: 'level-1-1', text: 'Level 1.1', icon: 'fa-home' },
				   { id: 'level-1-2', text: 'Level 1.2', icon: 'fa-star' },
				   { id: 'level-1-3', text: 'Level 1.3', icon: 'fa-check' }
				 ]
		},
		{ id: 'level-2', text: 'Level 2', img: 'icon-folder', expanded: true, group: true,
		  nodes: [ { id: 'level-2-1', text: 'Level 2.1', img: 'icon-folder',
					 nodes: [
					   { id: 'level-2-1-1', text: 'Level 2.1.1', img: 'icon-page' },
					   { id: 'level-2-1-2', text: 'Level 2.1.2', img: 'icon-page' },
					   { id: 'level-2-1-3', text: 'Level 2.1.3', img: 'icon-page' }
				 ]},
				   { id: 'level-2-2', text: 'Level 2.2', img: 'icon-page' },
				   { id: 'level-2-3', text: 'Level 2.3', img: 'icon-page' }
				 ]
		},
		{ id: 'level-3', text: 'Level 3', img: 'icon-folder', expanded: true, group: true,
		  nodes: [ { id: 'level-3-1', text: 'Level 3.1', img: 'icon-page' },
				   { id: 'level-3-2', text: 'Level 3.2', img: 'icon-page' },
				   { id: 'level-3-3', text: 'Level 3.3', img: 'icon-page' }
				 ]
		}
	],
	onClick: function (event) {
		w2ui['layout'].content('main', 'id: ' + event.target);
	}
}));

w2ui['layout'].content('top', $().w2toolbar({
  name: 'toolbar',
  items: [
    { type: 'check',  id: 'item1', caption: 'Check', img: 'icon-page', checked: true },
    { type: 'break',  id: 'break0' },
    { type: 'menu',   id: 'item2', caption: 'Drop Down', img: 'icon-folder', items: [
      { text: 'Item 1', icon: 'icon-page' },
      { text: 'Item 2', icon: 'icon-page' },
      { text: 'Item 3', value: 'Item Three', icon: 'icon-page' }
    ]},
    { type: 'break', id: 'break1' },
    { type: 'radio',  id: 'item3',  group: '1', caption: 'Radio 1', icon: 'fa-star', checked: true },
    { type: 'radio',  id: 'item4',  group: '1', caption: 'Radio 2', icon: 'fa-star-empty' },
    { type: 'spacer' },
    { type: 'button',  id: 'item5',  caption: 'Item 5', icon: 'fa-home' }
  ]
}));
```

The problem is that no fa-icon is visible. And when i change the icon to icon-page for example, it also doesn't work.

**Comment by mrg2001** [comment] 2017-01-03 22:13
Did you include FontAwesome css? All fa-* icons are part of font awesome library.

**Comment by mpf82** [comment] 2017-01-04 10:19
Possible duplicate of https://github.com/vitmalina/w2ui/issues/508

Try o also add the ``fa`` class to the icons (see my comment and example fiddle here: https://github.com/vitmalina/w2ui/issues/508#issuecomment-267899241)

**Comment by pierpaolocira** [comment] 2017-02-14 13:57
Yes @mpf82 , in my case replacing `icon: 'fa-star'` with `icon: 'fa fa-star'` it works.

**Comment by mpf82** [comment] 2017-02-14 14:52
@mrg2001 this issue can probably be closed. @ruttydm did not respond all January and this really is not a w2ui issue, but rather a matter of which version of font awesome library is used.

**Comment by mpf82** [comment] 2021-04-22 14:27
Closing issue: no response

**Closed by mpf82** 2021-04-22 14:27 UTC
