### ISSUE TITLE
w2form.url and remote data source

### ISSUE THREAD

**Issue by vfrom** [vitmalina/w2ui#2068] opened 2021-06-30 20:47 UTC
If the .url property is defined and .recid property is not 0, the form will attempt to load record data from the remote data source sending request:
_{
    cmd     : 'get-record',   // command
    name    : 'form',         // name of the form
    recid   : xx              // recid of the form
}_

So, the .url and .recid property is set and request is sending... Empty request.

Loading record data works perfectly in w2grid, but **w2form** sends empty request to the server. There is no any json value in it.

**Comment by vfrom** [comment] 2021-07-31 12:25
$(function () {
    $('#form').w2form({
        name  : 'form',
        url   : 'server/data',
        recid: 123,
        fields: [
            { field: 'first_name', type: 'text', required: true },
            { field: 'last_name',  type: 'text', required: true },
            { field: 'comments',   type: 'text'}
        ],
        actions: {
            reset: function () {
                this.clear();
            },
            save: function () {
                this.save();
            }
        }
    });
});

- request is null when loading data from 'url'

**Comment by mansurdegirmenci** [comment] 2021-07-31 18:45
![image](https://user-images.githubusercontent.com/38755096/127749631-42af38e5-13b1-4e53-aecc-0c82a56daa49.png)
I tried it and it works, I didn't see any problems.

**Comment by mpf82** [comment] 2021-09-17 11:02
I cannot reproduce this either.

Fiddle: http://jsfiddle.net/k6g27dn9/

The postdata in the request event looks fine:

```
   postData: {
    cmd: "get",
    name: "form",
    recid: 456
  },
```

Also, in your first post you write ``get-record`` - that looks like w2ui 1.4 or older.

I am closing this issue for now. If you want someone to look into it, please provide a fiddle that demonstrates the issue.

**Closed by mpf82** 2021-09-17 11:02 UTC
