### ISSUE TITLE
duplicated http request in the grid

### ISSUE THREAD

**Issue by atitoff** [vitmalina/w2ui#1885] opened 2020-03-09 13:16 UTC
* **I'm submitting a ...**
[ ] bug report

in night versions there is a bug
in version w2ui-1.5.rc1.js it is not

add
```js
            onRequest: function (event) {
                console.log('-- server call --');
                console.log(event);
                event.preventDefault()
            }
```

![pic](https://i111.fastpic.ru/big/2020/0309/c0/7d57f489df62fc660d058cc49f000bc0.png)

**Comment by mdavis1960** [comment] 2020-03-11 01:27
Related to #1883?  I pulled the latest code yesterday and see a similar issue reported in #1883

**Comment by mpf82** [comment] 2021-04-28 09:22
I cannot reproduce the issue: http://jsfiddle.net/oh3tuqrc/

Maybe it has been fixed in the meantime.

Can you please confirm it's fixed or create a fiddle to demonstrate the issue?

**Comment by mpf82** [comment] 2021-04-28 09:22
I cannot reproduce the issue: http://jsfiddle.net/oh3tuqrc/

Maybe it has been fixed in the meantime.

Can you please confirm it's fixed or create a fiddle to demonstrate the issue?

**Comment by mpf82** [comment] 2021-06-09 08:38
Closing issue: no response

**Closed by mpf82** 2021-06-09 08:38 UTC
Labels: Waiting For Reply
