### ISSUE TITLE
Master branch, server side

### ISSUE THREAD

**Issue by Kirua88** [vitmalina/w2ui#1339] opened 2016-09-28 09:18 UTC
"remote data is not compatible with grid " in js file
really ??

but i saw you have java and php example for that...

thats's why i get 404 error when i replace 1.4.3 version by master ?
i thought it was the way to get request parameter, so i try different way but always 404 error.

I really don't understand, if someone can help.

**Comment by mpf82** [comment] 2016-09-28 11:07
The default value of `w2utils.settings.dataType` has changed from `HTTP` to `HTTPJSON`.

This setting has an influence on the AJAX communication.

The possible values are as follows (taken from the JS file):

> can be HTTP, HTTPJSON, RESTFULL, RESTFULLJSON, JSON (case sensitive)

This *might* be the reason for your 404 error, though it *should* rather result in a `415 Unsupported Media Type` error.

You should also check your browser's network tab to see what URL is called and what parameters you're sending.

Also note that the server commands have changed. For example, instead of `get-records` it's now only `get`.

**Comment by Kirua88** [comment] 2016-09-28 11:36
Okay thanks

but i try several possibility but nothing yet.
i'm using .net, that's a little different from php or java i think.

**Comment by Kirua88** [comment] 2016-09-28 14:32
If someone already use it with .net, feel free to help me.
thks

**Comment by chalchis** [comment] 2016-09-28 14:37
attempts to return
in your code JSON
no matter the programming language

**Comment by Kirua88** [comment] 2016-09-28 14:43
The problem is that my method in controller is not called at all.
Breakpoint don't even fired in visual studio.
I'm sure the problem is the parameters, but didn't find the right combo yet

**Comment by Kirua88** [comment] 2016-09-29 06:49
I also try to force w2utils.settings.dataType to HTTP, it worked but a bug with the expand subgrid appear.
If someone using the master branch with .NET, tell me the solution

**Comment by mrg2001** [comment] 2016-10-03 04:55
404 - seems like it is a server side error. Make sure you working with correct verb (GET/POST...) on the server side. Most likely you just need to change that.

Since it is not a bug in the grid, I am closing the issue. You are welcome to continue discussion in this thread.

**Closed by mrg2001** 2016-10-03 04:55 UTC
