### ISSUE TITLE
z-index alert Field Types

### ISSUE THREAD

**Issue by kashimAstro** [vitmalina/w2ui#908] opened 2015-05-26 14:36 UTC
Hello Mr. vitmalina.

first of all, thank you for his work ..

I wanted to ask your advice, I have a layout divided in this way:
header
main
preview (default hide)
footer

I plugged in a preview widgets took its name examples "Field Types"
can you tell me how I can solve the z-index of the alert related to the "Field Types"

Image example:

![w2ui_alert_zindex](https://cloud.githubusercontent.com/assets/6746680/7814679/eb454f36-03c3-11e5-96e1-c95492a89e82.png)

Source test:

```
<!DOCTYPE html>
<html>
<head>
    <title>layout dynamica</title>
    <link rel="stylesheet" type="text/css" href="../UI_w2/w2ui-1.4.2.css" />
    <script src="../script/jquery.js"></script>
    <script type="text/javascript" src="../UI_w2/w2ui-1.4.2.js"></script>
</head>
<body>

<div id="layout" style="width:100%; height:800px"></div>

<script type="text/javascript">
$(function () {
    var pstyle = 'border: 1px solid #dfdfdf; padding: 5px;';
    w2utils.locale("it-it.json");

    $('#layout').w2layout({
        name: 'layout',
        panels: [
            { type: 'top',     size:  50, style: pstyle, content: '<b>Dynamica header</b>' },
            { type: 'preview', size: 300, style: pstyle, hidden: true, content: '<div id="form" style="width: 100%;height:400px;"></div>' },
            { type: 'main',    style: pstyle, content: '<div id="grid" style="width: 100%; height:400px;"></div>' },
            { type: 'bottom',  size:  50, style: pstyle, content: '<button class="btn" onclick="w2ui[\'layout\'].toggle(\'preview\', window.instant); ">preview</button>' }
        ]
    });

    w2ui.layout.on('resize', function(event) {
            $("#layout").height($(window).height()-18);
            if(w2ui['layout'].get('preview').hidden==false){
                $("#grid").height(w2ui['layout'].get('main').height-15);
                $("#form").height(w2ui['layout'].get('preview').size-15);
                }
            else
                $("#grid").height($(window).height()-140);
    });

    $('#grid').w2grid({
        name: 'grid',
        show: {
            toolbar: true,
            footer: true
        },
        multiSearch: true,
        searches: [
            { field: 'recid', caption: 'ID ', type: 'int' },
            { field: 'lname', caption: 'Last Name', type: 'text' },
            { field: 'fname', caption: 'First Name', type: 'text' },
            { field: 'email', caption: 'Email', type: 'list', options: { items: ['peter@gmail.com', 'jim@gmail.com', 'jdoe@gmail.com']} },
            { field: 'sdate', caption: 'Start Date', type: 'date' }
        ],
        columns: [
            { field: 'recid', caption: 'ID', size: '50px', sortable: true, attr: 'align=center' },
            { field: 'lname', caption: 'Last Name', size: '30%', sortable: true },
            { field: 'fname', caption: 'First Name', size: '30%', sortable: true },
            { field: 'email', caption: 'Email', size: '40%' },
            { field: 'sdate', caption: 'Start Date', render: 'date:mm/dd/yyyy', size: '120px' },
        ],
        records: [
            { recid: 1, fname: 'Jane', lname: 'Doe', email: 'jdoe@gmail.com', sdate: 384052483664 },
            { recid: 2, fname: 'Stuart', lname: 'Motzart', email: 'jdoe@gmail.com', sdate: 1384052583664 },
            { recid: 3, fname: 'Jin', lname: 'Franson', email: 'peter@gmail.com', sdate: 1383620688314 },
            { recid: 4, fname: 'Susan', lname: 'Ottie', email: 'jim@gmail.com', sdate: 1384052463664 },
            { recid: 5, fname: 'Kelly', lname: 'Silver', email: 'peter@gmail.com', sdate: 1383793476323 },
            { recid: 6, fname: 'Francis', lname: 'Gatos', email: 'jdoe@gmail.com', sdate: 1383620688314 },
            { recid: 7, fname: 'Mark', lname: 'Welldo', email: 'jim@gmail.com', sdate: 1383361499126 },
            { recid: 8, fname: 'Thomas', lname: 'Bahh', email: 'jdoe@gmail.com', sdate: 1383793476323 },
            { recid: 9, fname: 'Sergei', lname: 'Rachmaninov', email: 'jdoe@gmail.com', sdate: 1383620688314 },
            { recid: 20, fname: 'Jill', lname: 'Doe', email: 'jdoe@gmail.com', sdate: 1383361499126 },
            { recid: 21, fname: 'Frank', lname: 'Motzart', email: 'jdoe@gmail.com', sdate: 1384052383664 },
            { recid: 22, fname: 'Peter', lname: 'Franson', email: 'jdoe@gmail.com', sdate: 1383793476323 },
            { recid: 23, fname: 'Andrew', lname: 'Ottie', email: 'jdoe@gmail.com', sdate: 1384054483664 },
            { recid: 24, fname: 'Manny', lname: 'Silver', email: 'jdoe@gmail.com', sdate: 1383361499126 },
            { recid: 25, fname: 'Ben', lname: 'Gatos', email: 'peter@gmail.com', sdate: 1383793476323 },
            { recid: 26, fname: 'Doer', lname: 'Welldo', email: 'jdoe@gmail.com', sdate: 1383361499126 },
            { recid: 27, fname: 'Shashi', lname: 'Bahh', email: 'jim@gmail.com', sdate: 1384052483664 },
            { recid: 28, fname: 'Av', lname: 'Rachmaninov', email: 'jim@gmail.com', sdate: 1383620688314 }
        ]
    });

    $('#form').w2form({ 
        name     : 'form',
        url      : 'server/post',
        header   : 'Field Types',
        formURL  : 'data/form.html', 
        fields: [
            { field: 'field_text', type: 'text', required: true },
            { field: 'field_alpha', type: 'alphaNumeric', required: true },
            { field: 'field_int', type: 'int', required: true },
            { field: 'field_float', type: 'float', required: true },
            { field: 'field_date', type: 'date' },
            { field: 'field_list', type: 'list', required: true, 
                options: { items: ['Adams, John', 'Johnson, Peter', 'Lewis, Frank', 'Cruz, Steve', 'Donnun, Nick'] } },
            { field: 'field_enum', type: 'enum', required: true, 
                options: { items: ['Adams, John', 'Johnson, Peter', 'Lewis, Frank', 'Cruz, Steve', 'Donnun, Nick'] } },
            { field: 'field_textarea', type: 'text'}
        ],
        actions: {
            reset: function () {
                this.clear();
            },
            save: function () {
                var obj = this;
                this.save({}, function (data) { 
                    if (data.status == 'error') {
                        console.log('ERROR: '+ data.message);
                        return;
                    }
                    obj.clear();
                });
            }
        }
    });
});
</script>

</body>
</html>
```

thank you, and I wish you a good day!
Dario

**Comment by vitmalina** [comment] 2015-05-31 16:09
I do not understand what the problem is. I do not see on the picture the problem. Can you circle it?

**Comment by kashimAstro** [comment] 2015-06-01 07:54
Hello thanks for the reply!

excuse my English is really bad.
I want to hide the error alerts that go under the main layout.

I enclose a sample image:
![vitacode](https://cloud.githubusercontent.com/assets/6746680/7908298/01ac996c-0844-11e5-90c8-9597351971f0.png)

when the form is partially covered error alerts fields must not be visible.

thanks greetings!
Dario

**Comment by mpf82** [comment] 2021-09-14 14:05
Closing as a duplicate of #472

**Closed by mpf82** 2021-09-14 14:05 UTC
