### ISSUE TITLE
Bubble outside of window

### ISSUE THREAD

**Issue by alexey-vasyunin** [vitmalina/w2ui#1435] opened 2016-12-29 12:24 UTC
Hello!

I have grid with 100% width and last field with bubble only (just bubble icon). And window gets horizontal scroll when bubble shows, because bubble shows outside of window instead show with offset by horizontal.

![image](https://cloud.githubusercontent.com/assets/5081020/21543818/2b190da6-cde3-11e6-8614-c3c679b08868.png)

**Comment by avber** [comment] 2016-12-29 12:59
There is a similar problem with grid's buttons and overlays.

Suppose the advanced search button is located at the right side of a grid's toolbar and no buttons come after it. When the overlay appears, document body scrollbars are shown briefly. Overlay size and position should be calculated before overlay is shown.

**Comment by mpf82** [comment] 2017-11-02 22:35
You should be able to workaround this issue since this pr: https://github.com/vitmalina/w2ui/pull/1198
by specifying an array of positions.

Example:

        {
            "field": "machineid",
            "caption": "machineid",
            ...
            "info": {
                "options": {
                    "position": [
                        "left",
                        "right"
                    ]
                }
            }
        },

If you're still having an issue despite this workaround, please create a fiddle.

If this solves your problem, please close the issue.

Cheers =)

**Comment by mpf82** [comment] 2021-04-22 14:06
Closing issue: no response, no reproducer

**Closed by mpf82** 2021-04-22 14:06 UTC
