### ISSUE TITLE
w2popup.open and w2popup.load rendering issue

### ISSUE THREAD

**Issue by bala-murugan** [vitmalina/w2ui#1011] opened 2015-08-04 20:10 UTC
I use w2popup.load to load different pages of my Wizard type screen. After the lease of the Chrome Browser latest version - Version 44.0.2403.130 (64-bit) , I can find the Popup load is shifted diagonally around 15 px  when ever we issue a Open or Load call to w2popup and it comes back to the same position as the previous Page.

Steps to reproduce:

Step 1:
w2popup.open({
        title: 'Page1 Title',
        body: '<div class="w2ui-centered">Content of Page1</div>'
    });

Step2:
w2popup.open({
        title: 'Page2 Title',
        body: '<div class="w2ui-centered">Content of Page2</div>'
    });

Problem : Between the Step 1 to Step 2 , this Page shift problem happens.  
Attached the screen shots below:
<img width="951" alt="transitionpage1to2" src="https://cloud.githubusercontent.com/assets/7852102/9071430/21a54064-3aaa-11e5-84c9-53eab3c17192.png">
<img width="926" alt="page2" src="https://cloud.githubusercontent.com/assets/7852102/9071429/21a51468-3aaa-11e5-8946-89c7cab16523.png">
<img width="927" alt="page1" src="https://cloud.githubusercontent.com/assets/7852102/9071428/21a18956-3aaa-11e5-9039-ba9b58cbc9d0.png">

**Comment by vitmalina** [comment] 2015-09-06 23:37
I cannot reproduce this problem, but is sounds to be like it is CSS overwrite problem. Do you have some other libraries or your custom css code that might interfere. Try disabling them and keep plain w2ui to confirm this.

**Comment by bala-murugan** [comment] 2015-09-09 17:26
Thanks for the reply. I confirmed without any external css, I could simulate this issue.
Can you please check these steps, just to prove that it is not from my external css.
1)Open URL : http://w2ui.com/web/demos/#!combo/combo-1  (Just to load W2ui lib on browser)
2)Open the console 
3)Executed command 1 : w2popup.open({
title: 'Page1 Title',
body: 'Content of Page1'
});
4)Then executed Comand 2 : w2popup.open({
title: 'Page2 Title',
body: 'Content of Page2'
});

Result:
I can see the same issue . May be , it has to do something with the browser and version. 
I could simulate this on Chrome Latest versions(Version 45.0.2454.85) but not on Safari.

**Comment by vitmalina** [comment] 2015-09-12 19:13
If I repeat the steps, indeed something like this happens for a fraction of a second. I noticed that after chrome got updated some time ago. It was fixed in current master, but not in the 1.4 branch. The problem relates to css prospective property.

**Closed** 2015-10-21 00:23 UTC
