### ISSUE TITLE
Slow scrolling at grid by keyboard

### ISSUE THREAD

**Issue by Evgsurf** [vitmalina/w2ui#1151] opened 2016-02-02 06:55 UTC
Here http://w2ui.com/web/demo/grid 
If I press down arrow button at keyboard and do not up it, grid scrolls very very slow
The same with up arrow with another lags.
The same at another samples

**Comment by Evgsurf** [comment] 2016-02-02 06:56
I use CHROME 48.0.2564.97 (64-bit) at Ubuntu 14.04

**Comment by vitmalina** [comment] 2016-02-05 17:24
What os are you on? I tried ton osx (el capitan) and it seems fine. Here is what I did. I click on the link, selected first record and pressed key down and held it. It seemed fine.

**Comment by codingPF** [comment] 2016-02-07 20:04
Same for me on FF43...W10...
The selection (Record ID: xxx) overtakes the screen after the first or second "hickup".
After reaching the last record -  the screen stays scrolling...

**Comment by Evgsurf** [comment] 2016-02-12 07:05
I use CHROME 48.0.2564.97 (64-bit) at Ubuntu 14.04
The same at CHROME 48.0.2564.109 m at WIN7

**Comment by vitmalina** [comment] 2016-02-12 16:44
Can you share a screen recording?

**Comment by Evgsurf** [comment] 2016-02-15 08:16
here https://youtu.be/AhNEJOZnK6M
I guess You will understand Russian :)

**Comment by Mouse** [comment] 2016-04-07 10:24
For all, who need quick normal scroll without animation:
Line 4251 (version: 1.4.3)
`-            var t2 = t1 + Math.floor(records.height() / this.recordHeight);
-            if (ind == t1) records.animate({ 'scrollTop': records.scrollTop() - records.height() / 1.3 }, 250, 'linear');
-            if (ind == t2) records.animate({ 'scrollTop': records.scrollTop() + records.height() / 1.3 }, 250, 'linear');
-            if (ind < t1 || ind > t2) records.animate({ 'scrollTop': (ind - 1) * this.recordHeight });
+            var t2 = t1 + Math.floor(records.height() / this.recordHeight);  
+            if (ind == t1) records.scrollTop(records.scrollTop() - this.recordHeight);
+            if (ind == t2) records.scrollTop(records.scrollTop() + this.recordHeight);                    
+            if (ind < t1 || ind > t2) records.scrollTop((ind-1) * this.recordHeight);
`

**Comment by mrg2001** [comment] 2016-04-10 00:46
I think I found how to fix it. I have added $().stop() which stops previous animation. It seems to be better on Windows now. Close the issue if it works for you.

**Comment by mpf82** [comment] 2021-09-14 13:58
Closing issue: seems fixed with PR 1151, cannot reproduce

**Closed by mpf82** 2021-09-14 13:58 UTC
