### ISSUE TITLE
Remove all columns sidebar and tabs problems.

### ISSUE THREAD

**Issue by Mingscript** [vitmalina/w2ui#1566] opened 2017-04-12 15:01 UTC
Thank you for sharing w2ui on github. The w2ui is used for my project
development. I adjusted some of the coding and it may provide a better solution
for the program. In the beginning, I used a loop the solve the problem but I
think that the performance of loop is not good enough where the ID is a must to
know. Therefore, I changed the function of “remove” as it shows on the picture
below. Similarity, deleting sidebars and tabs appeared the same issue with the original
code and the solution is the same as solving the function of “remove”.
In order to prevent image upload failure, I put the code and the number of changes in the picture below.
My version is w2ui-1.5.rc1.min.js .
![remove tabs](https://cloud.githubusercontent.com/assets/21995558/24964050/c91251f2-1fd2-11e7-94e0-9905a7762d0a.png)
**remove all tabs.**
Row number 5722，remove function below.
 _removes:` function () {
            this.tabs = [];
        }_
![remove all sidebar](https://cloud.githubusercontent.com/assets/21995558/24964104/eabbf4fc-1fd2-11e7-9fb4-b0ce5874cadb.png)
**remove all sidebar.**
Row number 6438，remove function below.
_removes: function(){
          this.nodes = [];
          return this.refresh();
        }_
![remove all columns](https://cloud.githubusercontent.com/assets/21995558/24964115/ee046298-1fd2-11e7-88fd-8ce3d8e15562.png)
**remove all columns.**
Row number 1451，removeColumn function below.
removeColumns: function () {
            this.columns = [];
            return this.refresh();
        },

**Comment by Mingscript** [comment] 2017-04-13 12:32
![qb_4faw w6 j1 jjn 7 2](https://cloud.githubusercontent.com/assets/21995558/25004694/32a2af80-2088-11e7-9eb0-d8ce521b1157.png)
This is your solution.
@vitmalina

**Comment by mrg2001** [comment] 2017-04-18 23:21
Sorry, I do not follow what the problem is. Can you restate it?
```
this.columns = []
```
will create a new array. Not clear current. You could do this
```js
this.columns.splice(0, this.columns.length)
```

**Comment by Mingscript** [comment] 2017-04-19 02:22
我试过了，就是删除现在的,而且我的问题就是简单，快速的删除所有的tabs，nodes，columns，而且不需要知道recid.
@mrg2001

**Comment by mrg2001** [comment] 2017-04-19 15:37
Setting grid.columns = [] will do it for grid, similar for other objects. Isn't it working?

**Comment by Mingscript** [comment] 2017-04-20 02:54
I mean the way of thinking is the same, to solve the problem from the point of my current project, this I write my own several function is very practical, before I go to the website to find the ways to solve this, the picture above you can see, I want to know recid already, but also to write similar to loop through this program, I can't accept it. Anyway, now it's use, hope to have the same problems can also be used.
@mrg2001

**Comment by mrg2001** [comment] 2017-04-21 15:32
You can add/redefine a function to grid's prototype and then it will be in all grids. See w2obj in here http://w2ui.com/web/docs/1.5/utils. To load in html, you first load w2ui.js and then your w2ui_custom.js. This way you can have your own custom functionality without need to changing source code of w2ui. Then you can define you custom functions there.

Is there anything else in this ticket or I can close it?

**Comment by Mingscript** [comment] 2017-04-22 14:37
Why can't modify the source code, this approach I think there will be some people will need, and in the website, also asked to this, I have in the project implements this function, just hope, what need to also know.There is no other problem.thank you！

**Comment by mrg2001** [comment] 2017-04-23 14:41
The reason all custom changes are done in the separate file is that then you can easily update the library once it is changing. As for including this piece of code into the library, I do not see a point.

**Closed by mrg2001** 2017-04-23 14:41 UTC
